# Processing Data and Preparing Tokenizations

This notebook processes and analyzes PubMed abstracts and titles to detect diseases using various tokenization methods and SciSpacy's biomedical NER model.

Tokenization Methods:
1. **Simple Tokenization**: Basic whitespace and punctuation-based tokenization.
2. **Hugging Face Tokenization**: Tokenization using the Hugging Face `distilbert-base-uncased` model.
3. **Dictionary-Based Disease Detection**: Filtering tokens based on a predefined disease dictionary.
4. **SciSpacy Biomedical NER**: Using the `en_ner_bc5cdr_md` model to detect disease entities.


## 0. Libraries and Utility Functions

In [ ]:
import pandas as pd
import pyarrow.parquet as pq
import os
from tqdm import tqdm
import matplotlib.pyplot as plt
from collections import Counter
from pathlib import Path  
import numpy as np
from transformers import AutoTokenizer
from nltk.corpus import stopwords
import nltk
import gc
import psutil
from multiprocessing import cpu_count
import time
import scispacy
import spacy

### 1) read_parquet_in_batches - function

In [6]:
def read_parquet_in_batches_with_progress(file_path, batch_size):
    """
    Read a Parquet file in fixed-size row batches with a progress bar and per-chunk logging.

    Args:
        file_path (str): Path to the Parquet file.
        batch_size (int): Number of rows per batch.

    Returns:
        pd.DataFrame: Combined DataFrame after processing all batches.
    """
    parquet_file = pq.ParquetFile(file_path)
    
    total_rows = parquet_file.metadata.num_rows
    
    all_chunks = []
    
    with tqdm(total=total_rows, desc="Processing Batches", unit="rows") as pbar:
        for batch_number, batch in enumerate(parquet_file.iter_batches(batch_size=batch_size), start=1):
            df_batch = batch.to_pandas()
            
            all_chunks.append(df_batch)
            
            pbar.update(len(df_batch))
            
            print(f"Processed Chunk {batch_number}: {len(df_batch)} rows")
    
    combined_df = pd.concat(all_chunks, ignore_index=True)
    
    return combined_df

````
# EXAMPLE USAGE
if __name__ == "__main__":
    file_path = "Data/2.Processed/ModellingData/P1_all.parquet"
    batch_size = 100_000  # Define your desired chunk size
    
    df = read_parquet_in_batches_with_progress(file_path, batch_size)
    
    print(f"\nFinal DataFrame with {len(df)} rows:")
    df.head()
    ````


### 2) save_batches_to_parquet - function

In [7]:
def save_and_merge_in_batches(
    df: pd.DataFrame,
    batch_size: int,
    output_folder: str,
    final_filename: str = "final_merged.parquet",
    temp_batch_prefix: str = "temp_batch_"
):
    """
    Splits 'df' into multiple batches (size = batch_size), writes each batch to a Parquet file,
    then merges them into one final Parquet, with a progress bar showing how many batches are done.

    Steps:
    ------
    1) Creates subfolder 'temp_batches' in output_folder for batch files.
    2) For each chunk of rows:
       - Writes it to 'temp_batch_X.parquet'
       - Increments a progress bar
    3) Reads & merges all batch files into 'final_filename', then removes them.

    Returns:
    --------
    str -> path to the final merged Parquet file.
    """

    os.makedirs(output_folder, exist_ok=True)

    temp_folder = os.path.join(output_folder, "temp_batches")
    os.makedirs(temp_folder, exist_ok=True)

    total_rows = len(df)
    batch_count = (total_rows + batch_size - 1) // batch_size
    print(f"Splitting DataFrame of {total_rows} rows into {batch_count} batches (size={batch_size}).")

    temp_files = []
    current_row = 0
    batch_index = 1

    # -- 1) SAVE IN MULTIPLE BATCHES WITH A PROGRESS BAR FOR THE BATCHES --
    with tqdm(total=batch_count, desc="Saving Batches", unit="batch") as pbar:
        while current_row < total_rows:
            end_row = min(current_row + batch_size, total_rows)
            df_batch = df.iloc[current_row:end_row]

            temp_file_name = f"{temp_batch_prefix}{batch_index}.parquet"
            temp_file_path = os.path.join(temp_folder, temp_file_name)

            df_batch.to_parquet(temp_file_path, index=False, compression="snappy")

            temp_files.append(temp_file_path)

            pbar.update(1)

            print(f"  -> Batch {batch_index} rows [{current_row}:{end_row}] saved to {temp_file_path}")

            current_row = end_row
            batch_index += 1

    # -- 2) MERGE ALL BATCH FILES INTO A SINGLE PARQUET --
    final_file_path = os.path.join(output_folder, final_filename)
    print(f"\nMerging {len(temp_files)} batch files into {final_file_path}...")

    merged_parts = []
    with tqdm(total=len(temp_files), desc="Merging Batches", unit="file") as pbar_merge:
        for file_path in temp_files:
            merged_parts.append(pd.read_parquet(file_path))
            pbar_merge.update(1)

    df_merged = pd.concat(merged_parts, ignore_index=True)
    df_merged.to_parquet(final_file_path, index=False, compression="snappy")
    print(f"Final merged DataFrame saved as: {final_file_path}\n")

    # -- 3) CLEAN UP TEMPORARY FILES --
    for path in temp_files:
        os.remove(path)
    os.rmdir(temp_folder)

    print("Temporary batch files removed. All done!")
    return final_file_path

````
# ---------------------------
# EXAMPLE USAGE
# ---------------------------
if __name__ == "__main__":

    folder_path = "Data/2.Processed/ModellingData"
    final_file = "P4_final_merged.parquet"
    batch_size = 100_000  # e.g. if you want ~10 batches

    result_path = save_and_merge_in_batches(
        df=df_final,
        batch_size=batch_size,
        output_folder=folder_path,
        final_filename=final_file,
        temp_batch_prefix="temp_batch_"
    )

    print(f"All done. Merged file at: {result_path}")
````

## 1. Early Processing 

*removing NA + filtering rows with wrong dates* (after 2024 and before 1995 articles will be excluded, as currently its 2024, and 1994 had low amount of articles)

### Step 0: Setup

In [5]:
df = pd.read_parquet("Data/1.EarlyCleaned/cleaned_parquet/final/PubMedAbstracts_final.parquet")
df.head()

uid                                              title  \
0  10150804  Evaluation of survival in medically treated pa...   
1   9061841  Cohort versus cross-sectional design in large ...   
2   9061840  Network analytic methods for epidemiological r...   
3   9061838  Estimating age, period and cohort effects usin...   
4  16353609  A perspective on the hormonal abnormalities of...   

                                          journal      pubdate  \
0  Journal of insurance medicine (New York, N.Y.)   None-01-01   
1                          Statistics in medicine  1994-Jan-15   
2                          Statistics in medicine  1994-Jan-15   
3                          Statistics in medicine  1994-Jan-15   
4                                Obesity research  1994-Jan-01   

                                            abstract  \
0  General: Articles published in medical journal...   
1  General: In planning large longitudinal field ...   
2  General: The authors measure the efficacy of t...   
3  General: To understand cancer aetiology better...   
4  General: Studies in our laboratory and elsewhe...   

                                             authors  \
0                                       Iacovino J R   
1                          Feldman H A; McKinlay S M   
2  Altmann M; Wee B C; Willard K; Peterson D; Gat...   
3                    Holford T R; Zhang Z; McKay L A   
4                               Zumoff B; Strain G W   

                                        affiliations  \
0    New York Life Insurance Company, New York, USA.   
1  New England Research Institute, Inc., Watertow...   
2  Division of Health Computer Sciences, Universi...   
3  Department of Epidemiology and Public Health, ...   
4  Division of Endocrinology and Metabolism, Depa...   

                                          mesh_terms keywords coi_statement  \
0  Adolescent; Adult; Age Distribution; Chelation...                    N/A   
1  Analysis of Variance; Cluster Analysis; Cohort...                    N/A   
2  Analysis of Variance; Communicable Disease Con...                    N/A   
3  Age Factors; Cell Transformation, Neoplastic; ...                    N/A   
4  Adolescent; Adult; Estradiol; Estrone; Female;...                    N/A   

         date parsed_date  
0  1994-01-01  1994-01-01  
1  1994-01-01  1994-01-15  
2  1994-01-01  1994-01-15  
3  1994-01-01  1994-01-15  
4  1994-01-01  1994-01-01

In [6]:
df.isna().sum()

uid               0
title             0
journal           0
pubdate           0
abstract         14
authors           0
affiliations      0
mesh_terms        0
keywords          0
coi_statement     0
date              0
parsed_date       0
dtype: int64

### **Step 1**: Filtering rows + removal of missing records 

(missing abstracts are, after checking manually, missing from articles itself, they are **NOT** due to mistakes in the processing or during phase of data gathering)

In [7]:
missing_abstracts = df[df["abstract"].isna()]
print("Rows where 'abstract' is missing:")
missing_abstracts

Rows where 'abstract' is missing:


uid                                              title  \
13973    7479089  Transverse temperature-gradient single-strand ...   
396952  19951381  Probing the limits of regional tissue oxygenat...   
714156  28549132  Selective impairment of goal-directed decision...   
748429  29240851                   Off Target But Hitting the Mark.   
771404  30496332  Towards Scalable Hospital-Based Palliative Car...   
771443  30475933  The vaginal wellness consultation for treatmen...   
775681  30667412  Nudging Providers to Improve Sleep for Hospita...   
775682  30667405  The Journal of Hospital Medicine in 2019 and B...   
776638  30534643  Clinical Operations Research: A New Frontier f...   
792798  31010740  RETRACTED: Comprehensive Analysis of the Expre...   
801191  31517334  Response to lubiprostone in chronic constipati...   
844289  32919413  Reopening Endoscopy after the COVID-19 Outbrea...   
890623  34212926  Paraquat lung - a rare cause of diffuse parenc...   
903522  34538297  Impact of COVID-19 on Pediatric Immunocompromi...   

                                                  journal      pubdate  \
13973                              Nucleic acids research  1995-Oct-25   
396952                    Critical care (London, England)   2009-01-01   
714156                     Brain : a journal of neurology  2017-Jun-01   
748429                       Journal of hospital medicine  2018-Apr-01   
771404                       Journal of hospital medicine  2018-Dec-01   
771443         Seminars in cutaneous medicine and surgery  2018-Dec-01   
775681                       Journal of hospital medicine  2019-Jan-01   
775682                       Journal of hospital medicine  2019-Jan-01   
776638                       Journal of hospital medicine  2019-Jan-08   
792798  Molecular therapy : the journal of the America...  2019-Jun-05   
801191  Journal of gastrointestinal and liver diseases...  2019-Sep-01   
844289  Journal of gastrointestinal and liver diseases...  2020-Sep-09   
890623                 Acta bio-medica : Atenei Parmensis  2021-Jul-01   
903522                 Pediatric clinics of North America  2021-Oct-01   

       abstract                                            authors  \
13973      None  Grace M B; Bambeck G S; Buzard G S; Weintraub B D   
396952     None                     Pinsky Michael R; Payen Didier   
714156     None  Reber Justin; Feinstein Justin S; O'Doherty Jo...   
748429     None  Kara Areeba; Mookherjee Somnath; Gavin Warren;...   
771404     None            Courtright Katherine R; O'Connor Nina R   
771443     None                                     Miller Misha D   
775681     None               Auriemma Catherine L; Greysen S Ryan   
775682     None                                       Shah Samir S   
776638     None                        Kohn Rachel; Greysen S Ryan   
792798     None  Sun Cheng-Cao; Li Shu-Jun; Hu Wei; Zhang Jian;...   
801191     None  Tarasiuk Aleksandra; Milad Mena; Ahmed Syed T;...   
844289     None  Elli Luca; Tontini Gian Eugenio; Scaramella Lu...   
890623     None  Agarwal Mehul; Gupta Manohar Lal; Deokar Kunal...   
903522     None  Connelly James A; Chong Hey; Esbenshade Adam J...   

                                             affiliations  \
13973   Diabetes and Digestive and Kidney Diseases, Na...   
396952  Critical Care Medicine, Bioengineering, Cardio...   
714156  Department of Psychological and Brain Sciences...   
748429  Inpatient Medicine, Indiana University Health ...   
771404  Division of Pulmonary, Allergy, and Critical C...   
771443  Mohs Micrographic Surgery and Cutaneous Oncolo...   
775681  Division of Pulmonary and Critical Care Medici...   
775682  Divisions of Hospital Medicine and Infectious ...   
776638  Department of Medicine, Perelman School of Med...   
792798  Department of Occupational and Environmental H...   
801191  Department of Biochemistry, Medical University...   
844289  Gastroenterology and Endoscopy Unit, Fondazio

In [8]:
x = (df.shape)

# 1) Drop rows with missing abstract (14) -> We have looked into them and it's really like they are missing abstract not due to fault that comes from coding but they are just empty on website. they contribute to ~ 1% of dataset so it is not much of an issue
df = df.dropna(subset=["abstract"])

print("Removed missing abstract rows:")
print(x[0]-df.shape[0])

# 2) Drop rows with year == 2025
# first ensure parsed_date is datetime
df["parsed_date"] = pd.to_datetime(df["parsed_date"], errors="coerce")

#df = df[df["parsed_date"].dt.year != 2025]
# Exclude years 1994 and 2025 ; 1994 has low amount of articles
df = df[(df["parsed_date"].dt.year != 1994) & (df["parsed_date"].dt.year != 2025)]

print("Removed total rows:")
print(x[0] - df.shape[0])

Removed missing abstract rows:
14
Removed total rows:
1890


In [9]:
# Selecting only columns that we will be working with
df = df[["uid", "title", "journal", "abstract", "authors", "affiliations", "mesh_terms", "keywords", "coi_statement", "parsed_date"]].copy()

## 2.  Simple and hugging face tokenization 

### 2.1. Tokenization

In [12]:
# Hugging Face tokenizer
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

def huggingface_tokenize(text, max_len=512):
    """
    Tokenize text with the Hugging Face tokenizer and truncate to max_len.
    """
    if not isinstance(text, str) or not text.strip():
        return []
    encoding = tokenizer.encode_plus(
        text,
        add_special_tokens=True,
        max_length=max_len,
        truncation=True,
        return_token_type_ids=False,
        return_attention_mask=False
    )
    return tokenizer.convert_ids_to_tokens(encoding["input_ids"])

def simple_tokenize(text):
    """
    Simple whitespace and punctuation-based tokenizer.
    """
    import re
    if not isinstance(text, str) or not text.strip():
        return []
    text = text.lower()
    text = re.sub(r"[^a-z\s]", " ", text)
    return text.split()

# Batch processing with progress bar
def process_in_batches(df, column, batch_size=1000, tokenizer_func=None, output_column=None, save_path=None):
    tqdm.pandas()  # Enables progress_apply with tqdm

    # Load existing processed results if the file exists
    if save_path and Path(save_path).exists():
        processed = pd.read_parquet(save_path)
        print(f"Loaded existing results from {save_path}.")
        return processed

    num_batches = (len(df) + batch_size - 1) // batch_size  # Total number of batches
    results = []

    for i in tqdm(range(num_batches), desc="Processing Batches"):
        start = i * batch_size
        end = start + batch_size

        # Process batch and avoid direct assignment to a slice
        batch = df.iloc[start:end]
        tokenized_data = batch[column].progress_apply(tokenizer_func)
        tokenized_df = pd.DataFrame({output_column: tokenized_data}, index=batch.index)
        results.append(tokenized_df)

        # Save progress after each batch
        if save_path:
            pd.concat(results).to_parquet(save_path, index=True)

    return pd.concat(results)

In [13]:
# Process title with both tokenizers
df["title_tokens_simple"] = process_in_batches(
    df, "title", batch_size=100_000, tokenizer_func=simple_tokenize, output_column="title_tokens_simple", save_path="Data/2.Processed/ModellingData/P0.simple_tokens_title.parquet"
)

df["title_tokens_hf"] = process_in_batches(
    df, "title", batch_size=100_000, tokenizer_func=lambda txt: huggingface_tokenize(txt, max_len=512), output_column="title_tokens_hf", save_path="Data/2.Processed/ModellingData/P0.hf_tokens_title.parquet"
)

Loaded existing results from Data/2.Processed/ModellingData/P0.simple_tokens_title.parquet.
Loaded existing results from Data/2.Processed/ModellingData/P0.hf_tokens_title.parquet.


In [14]:
# Process title with both tokenizers
df["abstract_tokens_simple"] = process_in_batches(
    df, "abstract", batch_size=100_000, tokenizer_func=simple_tokenize, output_column="abstract_tokens_simple", save_path="Data/2.Processed/ModellingData/P0.simple_tokens_abstract.parquet"
)

df["abstract_tokens_hf"] = process_in_batches(
    df, "abstract", batch_size=100_000, tokenizer_func=lambda txt: huggingface_tokenize(txt, max_len=512), output_column="abstract_tokens_hf", save_path="Data/2.Processed/ModellingData/P0.hf_tokens_abstract.parquet"
)

Loaded existing results from Data/2.Processed/ModellingData/P0.simple_tokens_abstract.parquet.
Loaded existing results from Data/2.Processed/ModellingData/P0.hf_tokens_abstract.parquet.


In [15]:
df.head()

uid                                              title  \
930  10186596  The potential impact of health care reform on ...   
931  10186588  New Jersey health promotion and disease preven...   
932  10186587  Who will provide preventive services? The chan...   
933  10163501  Cytoreduction of small intestine metastases us...   
934  10157383  Racial differences in access to kidney transpl...   

                                               journal  \
930  Journal of public health management and practi...   
931  Journal of public health management and practi...   
932  Journal of public health management and practi...   
933                     Journal of gynecologic surgery   
934                       Health care financing review   

                                              abstract  \
930  General: This article observes that, despite t...   
931  General: Health promotion is a major component...   
932  General: Health care reform in the United Stat...   
933  General: The Cavitron Ultrasonic Surgical Aspi...   
934  General: Previous work has documented large di...   

                               authors  \
930              Auerbach J; McGuire J   
931                         Louria D B   
932  Pearson T A; Spencer M; Jenkins P   
933                        Adelson M D   
934                         Eggers P W   

                                          affiliations  \
930  HIV/AIDS Bureau, Massachusetts Department of P...   
931  Department of Preventive Medicine and Communit...   
932  Mary Imogene Bassett Research Institute, Coope...   
933  Department of Obstetrics and Gynecology, Crous...   
934  Office of Research and Demonstrations, Health ...   

                                            mesh_terms  \
930  Financing, Government; HIV Infections; Health ...   
931  Female; Health Education; Health Promotion; Hu...   
932  Delivery of Health Care; Female; Health Care R...   
933  Adenocarcinoma; Fallopian Tube Neoplasms; Fema...   
934  Adolescent; Adult; Black or African American; ...   

                                              keywords coi_statement  \
930                                                              N/A   
931                                                              N/A   
932                                                              N/A   
933                                                              N/A   
934  Empirical Approach; End Stage Renal Disease Pr...           N/A   

    parsed_date                                title_tokens_simple  \
930  1995-01-01  [the, potential, impact, of, health, care, ref...   
931  1995-01-01  [new, jersey, health, promotion, and, disease,...   
932  1995-01-01  [who, will, provide, preventive, services, the...   
933  1995-01-01  [cytoreduction, of, small, intestine, metastas...   
934  1995-01-01  [racial, differences, in, access, to, kidney, ...   

                                       title_tokens_hf  \
930  [[CLS], the, potential, impact, of, health, ca...   
931  [[CLS], new, jersey, health, promotion, and, d...   
932  [[CLS], who, will, provide, prevent, ##ive, se...   
933  [[CLS], cy, ##tore, ##duction, of, small, int,...   
934  [[CLS], racial, differences, in, access, to, k...   

                                abstract_tokens_simple  \
930  [general, this, article, observes, that, despi...   
931  [general, health, promotion, is, a, major, com...   
932  [general, health, care, reform, in, the, unite...   
933  [general, the, cavitron, ultrasonic, surgical,...   
934  [general, previous, work, has, documented, lar...   

                                    abstract_tokens_hf  
930  [[CLS], general, :, this, article, observes, t...  
931  [[CLS], general, :, health, promotion, is, a, ...  
932  [[CLS], general, :, health, care, reform, in, ...  
933  [[CLS], general, :, the, ca, ##vi, ##tron, ult...  
934  [[CLS], general, :, previous, work, has, docum...

### 2.2 Insight into simple and hugging face tokenization

In [16]:
# Flatten token lists and count token frequencies
simple_token_flat = [token for tokens in df["title_tokens_simple"] for token in tokens]
hf_token_flat = [token for tokens in df["title_tokens_hf"] for token in tokens]

# Count frequencies
simple_token_freq = Counter(simple_token_flat).most_common(20)
hf_token_freq = Counter(hf_token_flat).most_common(20)

# Convert to DataFrame for visualization
freq_df = pd.DataFrame({
    "Simple Tokens": [token for token, _ in simple_token_freq],
    "Simple Frequency": [freq for _, freq in simple_token_freq],
    "HF Tokens": [token for token, _ in hf_token_freq],
    "HF Frequency": [freq for _, freq in hf_token_freq]
})

print(freq_df)

   Simple Tokens  Simple Frequency HF Tokens  HF Frequency
0             of            752824     [CLS]       1057871
1            and            580862     [SEP]       1057871
2             in            564871         .       1054533
3            the            394711        of        752918
4              a            297509         -        621026
5           with            227261       and        582873
6            for            203622        in        581329
7        disease            138489       the        400449
8             to            133638         :        335712
9       patients             99181         a        290922
10            on             73151      with        227337
11        cancer             71336         ,        208135
12         study             68646       for        203958
13          from             56280   disease        138753
14     treatment             54923        to        136885
15            an             54461       ##s        1340

In [17]:
# Flatten token lists and count token frequencies
simple_token_flat = [token for tokens in df["abstract_tokens_simple"] for token in tokens]
hf_token_flat = [token for tokens in df["abstract_tokens_hf"] for token in tokens]

# Count frequencies
simple_token_freq = Counter(simple_token_flat).most_common(20)
hf_token_freq = Counter(hf_token_flat).most_common(20)

# Convert to DataFrame for visualization
freq_df = pd.DataFrame({
    "Simple Tokens": [token for token, _ in simple_token_freq],
    "Simple Frequency": [freq for _, freq in simple_token_freq],
    "HF Tokens": [token for token, _ in hf_token_freq],
    "HF Frequency": [freq for _, freq in hf_token_freq]
})

print(freq_df)

   Simple Tokens  Simple Frequency HF Tokens  HF Frequency
0            the           9007908         .      12749311
1             of           8798344         ,      10883008
2            and           8345723       the       8894333
3             in           5595886        of       8613396
4             to           4427437       and       8185741
5              a           3543218         -       6632571
6           with           3297571        in       5635904
7            for           2471641         )       4660852
8       patients           1706513         (       4639568
9           were           1699731        to       4354021
10           was           1561049         a       3393098
11            is           1560850      with       3211453
12          that           1419716         :       2723088
13            or           1157258       for       2410120
14            as           1071864       ##s       1885318
15       disease           1034488         %       17542

### 2.3. Cleaning simple and hugging face tokenization

In [18]:
# Download stopwords from NLTK
nltk.download("stopwords")

# Get the list of stopwords
stop_words = set(stopwords.words("english"))

# Remove stopwords from the tokens titles
df["cleaned_title_tokens_simple"] = df["title_tokens_simple"].apply(lambda tokens: [t for t in tokens if t not in stop_words])
df["cleaned_title_tokens_hf"] = df["title_tokens_hf"].apply(lambda tokens: [t for t in tokens if t not in stop_words])

# Remove stopwords from the tokens abstracts
df["cleaned_abstract_tokens_simple"] = df["abstract_tokens_simple"].apply(lambda tokens: [t for t in tokens if t not in stop_words])
df["cleaned_abstract_tokens_hf"] = df["abstract_tokens_hf"].apply(lambda tokens: [t for t in tokens if t not in stop_words])

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\macie\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [19]:
punctuation_tokens = {".", ",", "-", ":", ";", "(", ")", "[", "]", "{", "}", "`", "'"}
def remove_punctuation(tokens):
    return [t for t in tokens if t not in punctuation_tokens]

# Then:
df["cleaned_title_tokens_simple"] = df["cleaned_title_tokens_simple"].apply(remove_punctuation).copy()
df["cleaned_title_tokens_hf"] = df["cleaned_title_tokens_hf"].apply(remove_punctuation).copy()

# Then:
df["cleaned_abstract_tokens_simple"] = df["cleaned_abstract_tokens_simple"].apply(remove_punctuation).copy()
df["cleaned_abstract_tokens_hf"] = df["cleaned_abstract_tokens_hf"].apply(remove_punctuation).copy()

In [ ]:
# Flatten token lists and count token frequencies
simple_token_flat = [token for tokens in df["cleaned_title_tokens_simple"] for token in tokens]
hf_token_flat = [token for tokens in df["cleaned_title_tokens_hf"] for token in tokens]

# Count frequencies
simple_token_freq = Counter(simple_token_flat).most_common(50)
hf_token_freq = Counter(hf_token_flat).most_common(50)

# Convert to DataFrame for visualization
freq_df = pd.DataFrame({
    "Simple Tokens": [token for token, _ in simple_token_freq],
    "Simple Frequency": [freq for _, freq in simple_token_freq],
    "HF Tokens": [token for token, _ in hf_token_freq],
    "HF Frequency": [freq for _, freq in hf_token_freq]
})

print(freq_df)

In [ ]:
# Flatten token lists and count token frequencies
simple_token_flat = [token for tokens in df["cleaned_abstract_tokens_simple"] for token in tokens]
hf_token_flat = [token for tokens in df["cleaned_abstract_tokens_hf"] for token in tokens]

# Count frequencies
simple_token_freq = Counter(simple_token_flat).most_common(50)
hf_token_freq = Counter(hf_token_flat).most_common(50)

# Convert to DataFrame for visualization
freq_df = pd.DataFrame({
    "Simple Tokens": [token for token, _ in simple_token_freq],
    "Simple Frequency": [freq for _, freq in simple_token_freq],
    "HF Tokens": [token for token, _ in hf_token_freq],
    "HF Frequency": [freq for _, freq in hf_token_freq]
})

print(freq_df)

### 2.4. Conclusions 

Based on our initial exploration, both simple tokenization and Hugging Face-based tokenization appear to be riable approaches for our research. 

However, cleaning required for these methods may prove to be overly time-intensive. 

As a result, we will prioritize alternative approaches for the time being. If these alternative methods fail to give satisfactory results, we will revisit and upgrade the tokenization-based strategy.

In [22]:
df.head()

uid                                              title  \
930  10186596  The potential impact of health care reform on ...   
931  10186588  New Jersey health promotion and disease preven...   
932  10186587  Who will provide preventive services? The chan...   
933  10163501  Cytoreduction of small intestine metastases us...   
934  10157383  Racial differences in access to kidney transpl...   

                                               journal  \
930  Journal of public health management and practi...   
931  Journal of public health management and practi...   
932  Journal of public health management and practi...   
933                     Journal of gynecologic surgery   
934                       Health care financing review   

                                              abstract  \
930  General: This article observes that, despite t...   
931  General: Health promotion is a major component...   
932  General: Health care reform in the United Stat...   
933  General: The Cavitron Ultrasonic Surgical Aspi...   
934  General: Previous work has documented large di...   

                               authors  \
930              Auerbach J; McGuire J   
931                         Louria D B   
932  Pearson T A; Spencer M; Jenkins P   
933                        Adelson M D   
934                         Eggers P W   

                                          affiliations  \
930  HIV/AIDS Bureau, Massachusetts Department of P...   
931  Department of Preventive Medicine and Communit...   
932  Mary Imogene Bassett Research Institute, Coope...   
933  Department of Obstetrics and Gynecology, Crous...   
934  Office of Research and Demonstrations, Health ...   

                                            mesh_terms  \
930  Financing, Government; HIV Infections; Health ...   
931  Female; Health Education; Health Promotion; Hu...   
932  Delivery of Health Care; Female; Health Care R...   
933  Adenocarcinoma; Fallopian Tube Neoplasms; Fema...   
934  Adolescent; Adult; Black or African American; ...   

                                              keywords coi_statement  \
930                                                              N/A   
931                                                              N/A   
932                                                              N/A   
933                                                              N/A   
934  Empirical Approach; End Stage Renal Disease Pr...           N/A   

    parsed_date                                title_tokens_simple  \
930  1995-01-01  [the, potential, impact, of, health, care, ref...   
931  1995-01-01  [new, jersey, health, promotion, and, disease,...   
932  1995-01-01  [who, will, provide, preventive, services, the...   
933  1995-01-01  [cytoreduction, of, small, intestine, metastas...   
934  1995-01-01  [racial, differences, in, access, to, kidney, ...   

                                       title_tokens_hf  \
930  [[CLS], the, potential, impact, of, health, ca...   
931  [[CLS], new, jersey, health, promotion, and, d...   
932  [[CLS], who, will, provide, prevent, ##ive, se...   
933  [[CLS], cy, ##tore, ##duction, of, small, int,...   
934  [[CLS], racial, differences, in, access, to, k...   

                                abstract_tokens_simple  \
930  [general, this, article, observes, that, despi...   
931  [general, health, promotion, is, a, major, com...   
932  [general, health, care, reform, in, the, unite...   
933  [general, the, cavitron, ultrasonic, surgical,...   
934  [general, previous, work, has, documented, lar...   

                                    abstract_tokens_hf  \
930  [[CLS], general, :, this, article, observes, t...   
931  [[CLS], general, :, health, promotion, is, a, ...   
932  [[CLS], general, :, health, care, reform, in, ...   
933  [[CLS], general, :, the, ca, ##vi, ##tron, ult...   
934  [[CLS], general, :, previous, work, has, docum...   

                           cleaned_title_tokens_sim

## 3. Dictionary-Based Disease Detection

In this approach, we manually create a disease dictionary. We then filter tokens to only keep tokens matching that dictionary. This is a straightforward method but can miss synonyms or multi-word diseases unless stored them as multiple entries.

### 3.1. Implementation

In [23]:
###############################################################################
# 1) Dictionary-Based Approach
###############################################################################

disease_dict = {
    # General and Common Diseases
    "cancer", "tumor", "diabetes", "hiv", "aids", "arthritis", "pneumonia",
    "hypertension", "influenza", "malaria", "tuberculosis", "dementia", "asthma", 
    "depression", "anxiety", "stroke", "heart disease", "kidney disease",
    
    # Infectious Diseases
    "hepatitis", "cholera", "dengue", "zika", "ebola", "typhoid", "plague",
    "meningitis", "measles", "rubella", "chickenpox", "shingles", "covid",
    "scarlet fever", "leprosy", "syphilis", "gonorrhea", "lyme disease",
    
    # Neurological Disorders
    "parkinson's disease", "epilepsy", "multiple sclerosis", "migraine", 
    "alzheimer's disease", "amyotrophic lateral sclerosis", "huntington's disease",
    "cerebral palsy", "autism", "adhd", "schizophrenia", "bipolar disorder",
    
    # Respiratory Diseases
    "bronchitis", "emphysema", "chronic obstructive pulmonary disease (copd)", 
    "sleep apnea", "pulmonary fibrosis", "cystic fibrosis",
    
    # Cardiovascular Diseases
    "high blood pressure", "arrhythmia", "coronary artery disease", 
    "heart failure", "heart attack", "aortic aneurysm", "angina",
    
    # Digestive Disorders
    "irritable bowel syndrome (ibs)", "ulcerative colitis", "crohn's disease",
    "gastritis", "peptic ulcer", "gastroesophageal reflux disease (gerd)",
    "pancreatitis", "hepatitis a", "hepatitis b", "hepatitis c",
    
    # Musculoskeletal Disorders
    "osteoporosis", "rheumatoid arthritis", "osteoarthritis", "gout",
    "fibromyalgia", "scoliosis", "spinal cord injury",
    
    # Endocrine Disorders
    "hyperthyroidism", "hypothyroidism", "cushing's syndrome", "addison's disease",
    "polycystic ovary syndrome (pcos)", "metabolic syndrome",
    
    # Skin Diseases
    "eczema", "psoriasis", "rosacea", "acne", "melanoma", "basal cell carcinoma",
    "squamous cell carcinoma",
    
    # Genetic Disorders
    "down syndrome", "turner syndrome", "klinefelter syndrome", 
    "sickle cell anemia", "cystic fibrosis", "marfan syndrome",
    
    # Blood Disorders
    "anemia", "leukemia", "lymphoma", "hemophilia", "thalassemia",
    "deep vein thrombosis", "pulmonary embolism",
    
    # Eye Diseases
    "cataracts", "glaucoma", "macular degeneration", "diabetic retinopathy",
    "conjunctivitis", "dry eye syndrome",
    
    # Liver Diseases
    "liver cirrhosis", "fatty liver disease", "hepatitis", "liver cancer",
    
    # Kidney and Urinary Diseases
    "kidney stones", "urinary tract infection (uti)", "chronic kidney disease",
    "nephritis", "prostate cancer", "bladder cancer",
    
    # Cancers
    "breast cancer", "lung cancer", "colon cancer", "skin cancer",
    "pancreatic cancer", "prostate cancer", "ovarian cancer", 
    "brain cancer", "thyroid cancer",
    
    # Reproductive Disorders
    "endometriosis", "ovarian cysts", "uterine fibroids", "erectile dysfunction",
    "infertility", "pelvic inflammatory disease (pid)",
    
    # Autoimmune Diseases
    "systemic lupus erythematosus", "hashimoto's disease", "sjogren's syndrome",
    "celiac disease", "graves' disease", "type 1 diabetes",
    
    # Others
    "sepsis", "allergies", "heat stroke", "hypothermia", "obesity",
    "metabolic syndrome", "malnutrition", "alcoholism", "drug addiction",
    "dyslexia", "anorexia", "bulimia", "hyperlipidemia", "bacterial vaginosis"
}



def keep_only_diseases(token_list):
    """
    Return only those tokens present in the disease_dict.
    We do a .lower() to unify. 
    If you have subwords in HF approach (like 'canc', '##er'),
    you might want to check partial matches or reconstruct them.
    """
    return [t for t in token_list if t.lower() in disease_dict]

In [24]:
# Example usage with cleaned columns:
df["disease_title_tokens_simple"] = df["cleaned_title_tokens_simple"].apply(keep_only_diseases)
df["disease_title_tokens_hf"] = df["cleaned_title_tokens_hf"].apply(keep_only_diseases)


disease_flat_simple = [tok for tokens in df["disease_title_tokens_simple"] for tok in tokens]
simple_disease_freq = Counter(disease_flat_simple).most_common(20)

disease_flat_hf = [tok for tokens in df["disease_title_tokens_hf"] for tok in tokens]
hf_disease_freq = Counter(disease_flat_hf).most_common(20)

print("Top 20 diseases title (simple):", simple_disease_freq)
print("Top 20 diseases title (HF):", hf_disease_freq)

Top 20 diseases title (simple): [('cancer', 71336), ('hiv', 29950), ('diabetes', 17710), ('covid', 15644), ('tumor', 12050), ('hepatitis', 8989), ('hypertension', 8285), ('depression', 7959), ('leukemia', 7908), ('obesity', 7316), ('arthritis', 7210), ('stroke', 6950), ('asthma', 6861), ('lymphoma', 6722), ('influenza', 6570), ('dementia', 6565), ('tuberculosis', 5689), ('schizophrenia', 5539), ('melanoma', 4653), ('aids', 3752)]
Top 20 diseases title (HF): [('cancer', 71420), ('hiv', 29984), ('diabetes', 17711), ('tumor', 12985), ('hepatitis', 8989), ('leukemia', 8157), ('depression', 7967), ('obesity', 7316), ('arthritis', 7213), ('asthma', 7209), ('influenza', 7034), ('dementia', 7011), ('stroke', 6957), ('tuberculosis', 5689), ('schizophrenia', 5543), ('pneumonia', 4403), ('aids', 3764), ('malaria', 3433), ('anxiety', 2755), ('autism', 2013)]


In [25]:
# Example usage with your cleaned columns:
df["disease_abstract_tokens_simple"] = df["cleaned_abstract_tokens_simple"].apply(keep_only_diseases)
df["disease_abstract_tokens_hf"] = df["cleaned_abstract_tokens_hf"].apply(keep_only_diseases)


disease_flat_simple = [tok for tokens in df["disease_abstract_tokens_simple"] for tok in tokens]
simple_disease_freq = Counter(disease_flat_simple).most_common(20)

disease_flat_hf = [tok for tokens in df["disease_abstract_tokens_hf"] for tok in tokens]
hf_disease_freq = Counter(disease_flat_hf).most_common(20)

print("Top 20 diseases abstract (simple):", simple_disease_freq)
print("Top 20 diseases abstract (HF):", hf_disease_freq)

Top 20 diseases abstract (simple): [('cancer', 373179), ('hiv', 204593), ('tumor', 149498), ('diabetes', 122518), ('covid', 81759), ('depression', 73186), ('hypertension', 65958), ('stroke', 63889), ('obesity', 58150), ('asthma', 54143), ('dementia', 43989), ('influenza', 37314), ('anxiety', 32909), ('hepatitis', 31614), ('schizophrenia', 27589), ('arthritis', 26089), ('lymphoma', 25888), ('aids', 24439), ('leukemia', 23992), ('melanoma', 23548)]
Top 20 diseases abstract (HF): [('cancer', 367292), ('hiv', 202203), ('tumor', 154808), ('diabetes', 119829), ('depression', 72342), ('stroke', 62292), ('obesity', 57074), ('asthma', 56798), ('dementia', 45508), ('influenza', 38891), ('anxiety', 32447), ('hepatitis', 31211), ('pneumonia', 28793), ('schizophrenia', 27382), ('arthritis', 25695), ('leukemia', 25399), ('aids', 24031), ('malaria', 22374), ('tuberculosis', 22043), ('autism', 8229)]


In [26]:
df.head()

uid                                              title  \
930  10186596  The potential impact of health care reform on ...   
931  10186588  New Jersey health promotion and disease preven...   
932  10186587  Who will provide preventive services? The chan...   
933  10163501  Cytoreduction of small intestine metastases us...   
934  10157383  Racial differences in access to kidney transpl...   

                                               journal  \
930  Journal of public health management and practi...   
931  Journal of public health management and practi...   
932  Journal of public health management and practi...   
933                     Journal of gynecologic surgery   
934                       Health care financing review   

                                              abstract  \
930  General: This article observes that, despite t...   
931  General: Health promotion is a major component...   
932  General: Health care reform in the United Stat...   
933  General: The Cavitron Ultrasonic Surgical Aspi...   
934  General: Previous work has documented large di...   

                               authors  \
930              Auerbach J; McGuire J   
931                         Louria D B   
932  Pearson T A; Spencer M; Jenkins P   
933                        Adelson M D   
934                         Eggers P W   

                                          affiliations  \
930  HIV/AIDS Bureau, Massachusetts Department of P...   
931  Department of Preventive Medicine and Communit...   
932  Mary Imogene Bassett Research Institute, Coope...   
933  Department of Obstetrics and Gynecology, Crous...   
934  Office of Research and Demonstrations, Health ...   

                                            mesh_terms  \
930  Financing, Government; HIV Infections; Health ...   
931  Female; Health Education; Health Promotion; Hu...   
932  Delivery of Health Care; Female; Health Care R...   
933  Adenocarcinoma; Fallopian Tube Neoplasms; Fema...   
934  Adolescent; Adult; Black or African American; ...   

                                              keywords coi_statement  \
930                                                              N/A   
931                                                              N/A   
932                                                              N/A   
933                                                              N/A   
934  Empirical Approach; End Stage Renal Disease Pr...           N/A   

    parsed_date  ...                             abstract_tokens_simple  \
930  1995-01-01  ...  [general, this, article, observes, that, despi...   
931  1995-01-01  ...  [general, health, promotion, is, a, major, com...   
932  1995-01-01  ...  [general, health, care, reform, in, the, unite...   
933  1995-01-01  ...  [general, the, cavitron, ultrasonic, surgical,...   
934  1995-01-01  ...  [general, previous, work, has, documented, lar...   

                                    abstract_tokens_hf  \
930  [[CLS], general, :, this, article, observes, t...   
931  [[CLS], general, :, health, promotion, is, a, ...   
932  [[CLS], general, :, health, care, reform, in, ...   
933  [[CLS], general, :, the, ca, ##vi, ##tron, ult...   
934  [[CLS], general, :, previous, work, has, docum...   

                           cleaned_title_tokens_simple  \
930  [potential, impact, health, care, reform, publ...   
931  [new, jersey, health, promotion, disease, prev...   
932  [provide, preventive, services, changing, rela...   
933  [cytoreduction, small, intestine, metastases, ...   
934  [racial, differences, access, kidney, transpla...   

                               cleaned_title_tokens_hf  \
930  [[CLS], potential, impact, health, care, refor...   
931  [[CLS], new, jersey, health, promotion, diseas...   
932  [[CLS], provide, prevent, ##ive, services, ?, ...   
933  [[CLS], cy, ##tore, ##duction, small, int, ##e...   
934  [[CLS], racial, differences, access, kidney, t...   

                     

### 3.2. Conlcusions

**Pros**:

Easy to implement.
You quickly see if “cancer” or “diabetes” is the top disease token.

**Cons**:

Multi-word diseases like “heart failure” or “chronic obstructive pulmonary disease” won’t match unless we store them as separate tokens or reconstruct them.

Subword issues: In Hugging Face tokens, “cancer” might appear as [canc, ##er]. That won’t match “cancer” in disease_dict unless we unify them.

## 4. SciSpacy Biomedical NER Approach

In this approach, We use a trained biomedical NER model (en_ner_bc5cdr_md) that can detect DISEASE entities in your text. This can handle multi-word diseases and synonyms automatically. 


### 4.1. Cleaning + Setting Up ENV with smaller dataframes

In [30]:

# Force the garbage collector to run
gc.collect()

0

In [33]:
df = df.drop(columns=["abstract_tokens_simple", "abstract_tokens_hf","title_tokens_simple","title_tokens_hf"]).copy()

In [34]:
if __name__ == "__main__":

    folder_path = "Data/2.Processed/ModellingData"
    final_file = "P1_all.parquet"
    batch_size = 100_000 
    
    result_path = save_and_merge_in_batches(
        df=df,
        batch_size=batch_size,
        output_folder=folder_path,
        final_filename=final_file,
        temp_batch_prefix="temp_batch_"
    )

    print(f"All done. Merged file at: {result_path}")

Splitting DataFrame of 1057871 rows into 11 batches (size=100000).


Saving Batches:   9%|▉         | 1/11 [00:08<01:28,  8.83s/batch]

  -> Batch 1 rows [0:100000] saved to Data/2.Processed/ModellingData\temp_batches\temp_batch_1.parquet


Saving Batches:  18%|█▊        | 2/11 [00:17<01:19,  8.78s/batch]

  -> Batch 2 rows [100000:200000] saved to Data/2.Processed/ModellingData\temp_batches\temp_batch_2.parquet


Saving Batches:  27%|██▋       | 3/11 [00:26<01:09,  8.74s/batch]

  -> Batch 3 rows [200000:300000] saved to Data/2.Processed/ModellingData\temp_batches\temp_batch_3.parquet


Saving Batches:  36%|███▋      | 4/11 [00:35<01:01,  8.79s/batch]

  -> Batch 4 rows [300000:400000] saved to Data/2.Processed/ModellingData\temp_batches\temp_batch_4.parquet


Saving Batches:  45%|████▌     | 5/11 [00:44<00:53,  8.88s/batch]

  -> Batch 5 rows [400000:500000] saved to Data/2.Processed/ModellingData\temp_batches\temp_batch_5.parquet


Saving Batches:  55%|█████▍    | 6/11 [00:54<00:47,  9.43s/batch]

  -> Batch 6 rows [500000:600000] saved to Data/2.Processed/ModellingData\temp_batches\temp_batch_6.parquet


Saving Batches:  64%|██████▎   | 7/11 [01:06<00:40, 10.11s/batch]

  -> Batch 7 rows [600000:700000] saved to Data/2.Processed/ModellingData\temp_batches\temp_batch_7.parquet


Saving Batches:  73%|███████▎  | 8/11 [01:17<00:31, 10.62s/batch]

  -> Batch 8 rows [700000:800000] saved to Data/2.Processed/ModellingData\temp_batches\temp_batch_8.parquet


Saving Batches:  82%|████████▏ | 9/11 [01:29<00:21, 10.89s/batch]

  -> Batch 9 rows [800000:900000] saved to Data/2.Processed/ModellingData\temp_batches\temp_batch_9.parquet


Saving Batches:  91%|█████████ | 10/11 [01:41<00:11, 11.25s/batch]

  -> Batch 10 rows [900000:1000000] saved to Data/2.Processed/ModellingData\temp_batches\temp_batch_10.parquet


Saving Batches: 100%|██████████| 11/11 [01:48<00:00,  9.84s/batch]


  -> Batch 11 rows [1000000:1057871] saved to Data/2.Processed/ModellingData\temp_batches\temp_batch_11.parquet

Merging 11 batch files into Data/2.Processed/ModellingData\P1_all.parquet...


Merging Batches: 100%|██████████| 11/11 [01:01<00:00,  5.64s/file]


Final merged DataFrame saved as: Data/2.Processed/ModellingData\P1_all.parquet

Temporary batch files removed. All done!
All done. Merged file at: Data/2.Processed/ModellingData\P1_all.parquet


In [35]:
df_title = df[['uid', 'title']].copy()
df_abstract = df[['uid', 'abstract']].copy()

In [36]:
# Folder and file paths
folder_path = "Data/2.Processed/ModellingData"

file_name_title = "P2_title.parquet"
file_name_abstract = "P2_abstract.parquet"

file_path_title = os.path.join(folder_path, file_name_title)
file_path_abstract = os.path.join(folder_path, file_name_abstract)

# 1. Save the DataFrame as a single Parquet file
df_title.to_parquet(file_path_title, index=False, compression="snappy")
print(f"DataFrame saved as a single Parquet file: {file_path_title}")

df_abstract.to_parquet(file_path_abstract, index=False, compression="snappy")
print(f"DataFrame saved as a single Parquet file: {file_path_abstract}")

DataFrame saved as a single Parquet file: Data/2.Processed/ModellingData\P2_title.parquet
DataFrame saved as a single Parquet file: Data/2.Processed/ModellingData\P2_abstract.parquet


In [37]:
# reseting ev for cleaning memory
%reset

In [38]:
# Print CPU usage percentage
print(f"CPU usage: {psutil.cpu_percent()}%")

# Print memory usage
memory_info = psutil.virtual_memory()
print(f"Memory usage: {memory_info.percent}%")

# Get the total number of CPUs
print(f"Number of CPUs available: {cpu_count()}")

CPU usage: 12.5%
Memory usage: 32.8%
Number of CPUs available: 12


### 4.2 SciSpacy Title

Processing `Title` with SciSpacy model

In [42]:
if __name__ == "__main__":
    file_path = "Data/2.Processed/ModellingData/P2_title.parquet"
    batch_size = 100_000  # Define your desired chunk size
    
    df_title = read_parquet_in_batches_with_progress(file_path, batch_size)
    
    print(f"\nFinal DataFrame with {len(df_title)} rows:")

Processing Batches:   0%|          | 0/1057871 [00:00<?, ?rows/s]

Processed Chunk 1: 100000 rows
Processed Chunk 2: 100000 rows
Processed Chunk 3: 100000 rows
Processed Chunk 4: 100000 rows
Processed Chunk 5: 100000 rows
Processed Chunk 6: 100000 rows
Processed Chunk 7: 100000 rows
Processed Chunk 8: 100000 rows
Processed Chunk 9: 100000 rows
Processed Chunk 10: 100000 rows
Processed Chunk 11: 57871 rows

Final DataFrame with 1057871 rows:


In [43]:
df_title.head()

uid                                              title
0  10186596  The potential impact of health care reform on ...
1  10186588  New Jersey health promotion and disease preven...
2  10186587  Who will provide preventive services? The chan...
3  10163501  Cytoreduction of small intestine metastases us...
4  10157383  Racial differences in access to kidney transpl...

In [44]:
###############################################################################
# COMPLETE CODE: CHUNK-BASED DISEASE EXTRACTION (BC5CDR) + TIME LEFT ESTIMATE
###############################################################################



###############################################################################
# 1) LOAD BC5CDR MODEL, DISABLING COMPONENTS FOR SPEED
###############################################################################
try:
    nlp_bc5cdr = spacy.load(
        "en_ner_bc5cdr_md", 
        disable=["tagger", "parser", "attribute_ruler", "lemmatizer"]
    )
except Exception as e:
    print("Could not load 'en_ner_bc5cdr_md'. Make sure you installed:")
    print("  pip install scispacy")
    print("  pip install en_ner_bc5cdr_md-0.5.4.tar.gz (or your local path)")
    raise e

def extract_diseases_spacy(doc):
    """
    Extract disease mentions from BC5CDR model. (ent.label_ in {CHEMICAL, DISEASE})
    We only keep label == 'DISEASE'.
    """
    diseases = []
    for ent in doc.ents:
        if ent.label_ == "DISEASE":
            diseases.append(ent.text)
    return diseases

###############################################################################
# 2) CHUNK PROCESSING WITH RESUME & TIME REMAIN ESTIMATE
###############################################################################
def process_diseases_in_chunks_with_resume(
    df,
    text_col="title",
    chunk_size=10_000,
    batch_size=32,
    save_path="partial_bc5cdr.parquet"
):
    """
    - df: main DataFrame
    - text_col: column with text to process
    - chunk_size: # of rows per chunk
    - batch_size: # docs per nlp.pipe() batch
    - save_path: Parquet file to store partial/final results

    1) Resumes from an existing partial file if it exists.
    2) Processes row by row in chunks, each chunk using spaCy's pipe for faster NER.
    3) Shows a progress bar + estimates time left based on chunk durations.
    4) Saves partial results after each chunk, then a final full save.
    5) The disease mentions get stored in df["disease_entities_spacy"].
    """
    # Reset index so row order is stable
    df = df.reset_index(drop=True)

    # Initialize the column if absent
    if "disease_entities_spacy" not in df.columns:
        df["disease_entities_spacy"] = None

    # Figure out how many rows are already done if partial file is found
    start_idx = 0
    if os.path.exists(save_path):
        try:
            partial_df = pd.read_parquet(save_path)
            if "disease_entities_spacy" in partial_df.columns:
                df["disease_entities_spacy"] = partial_df["disease_entities_spacy"]
                done_mask = df["disease_entities_spacy"].notna()
                done_rows = done_mask.sum()
                start_idx = done_rows
                print(f"Resuming from row {start_idx} based on partial file {save_path}.")
            else:
                print(f"WARNING: {save_path} lacks 'disease_entities_spacy'. Starting fresh.")
        except Exception as e:
            print(f"Error reading partial file {save_path}: {e}")
            print("Starting from scratch.")
    else:
        print("No partial file found. Starting from scratch.")

    total_rows = len(df)
    if start_idx >= total_rows:
        print(f"All {total_rows} rows processed. Nothing to do.")
        return df

    # Calculate how many chunks remain
    remaining = total_rows - start_idx
    num_chunks = (remaining + chunk_size - 1) // chunk_size
    print(f"Starting chunked processing from row {start_idx}/{total_rows}, "
          f"{remaining} rows left, {num_chunks} chunks.\n")

    cur_row = start_idx
    chunk_times = []  # keep track of each chunk's duration to estimate time left

    # Initialize the progress bar
    with tqdm(total=num_chunks, desc="Processing Chunks", unit="chunk") as pbar:
        for i in range(num_chunks):
            chunk_start_time = time.time()

            end_idx = min(cur_row + chunk_size, total_rows)
            chunk = df.iloc[cur_row:end_idx].copy()
            texts = chunk[text_col].fillna("").tolist()

            # We'll store the results
            results = []

            # Use spaCy pipe in batch
            for doc in nlp_bc5cdr.pipe(texts, batch_size=batch_size):
                diseases = extract_diseases_spacy(doc)
                results.append(diseases)

            # Store in chunk and main df
            chunk["disease_entities_spacy"] = results
            df.iloc[cur_row:end_idx, df.columns.get_loc("disease_entities_spacy")] = chunk["disease_entities_spacy"]

            # Partial save
            df.iloc[:end_idx].to_parquet(save_path, index=False)

            # Chunk timing
            chunk_duration = time.time() - chunk_start_time
            chunk_times.append(chunk_duration)
            chunks_done = i + 1
            chunks_left = num_chunks - chunks_done
            # average chunk time so far
            avg_chunk_time = sum(chunk_times) / chunks_done
            est_time_left = avg_chunk_time * chunks_left

            # Update progress bar description with estimated time left
            pbar.set_postfix({
                "Last Chunk Time": f"{chunk_duration:.1f}s",
                "Est. Time Left": f"{est_time_left/60:.1f} min"
            })
            pbar.update(1)

            cur_row = end_idx

    # Final full save
    df.to_parquet(save_path, index=False)
    print(f"All done! Full results saved to {save_path}.\n")
    return df

###############################################################################
# EXAMPLE USAGE
###############################################################################
if __name__ == "__main__":

    # Adjust chunk_size, batch_size to fit your environment
    df_title = process_diseases_in_chunks_with_resume(
        df_title,
        text_col="title",
        chunk_size=10_000,       # small chunk for demo
        batch_size=64,       # small batch for demo
        save_path="Data/2.Processed/ModellingData/P3_bc5cdr_results_title.parquet"
    )

    # Inspect final results
df_title[["title", "disease_entities_spacy"]]

Resuming from row 1057871 based on partial file Data/2.Processed/ModellingData/P3_bc5cdr_results_title.parquet.
All 1057871 rows processed. Nothing to do.


title  \
0        The potential impact of health care reform on ...   
1        New Jersey health promotion and disease preven...   
2        Who will provide preventive services? The chan...   
3        Cytoreduction of small intestine metastases us...   
4        Racial differences in access to kidney transpl...   
...                                                    ...   
1057866               Mental health help-seeking in China.   
1057867  Outcomes of Adenotonsillectomy for Obstructive...   
1057868  The Role of Puerarin in Chronic Wounds: A Revi...   
1057869  The Role of AMP-activated Protein Kinase in Ox...   
1057870  Spontaneous resolution of cerebral arterioveno...   

                                disease_entities_spacy  
0                                                   []  
1                                                   []  
2                                                   []  
3                                                   []  
4                                                   []  
...                                                ...  
1057866                                             []  
1057867  [Adenotonsillectomy, Obstructive Sleep Apnea]  
1057868                                             []  
1057869                                             []  
1057870          [cerebral arteriovenous malformation]  

[1057871 rows x 2 columns]

In [46]:
df_title['entity_count'] = df_title['disease_entities_spacy'].apply(len)

# 1. Value counts of the number of entities in lists
entity_count_value_counts = df_title['entity_count'].value_counts()

# 2. Binary categorization: 0 count or more than 0
df_title['has_entities'] = df_title['entity_count'].apply(lambda x: 1 if x > 0 else 0)

# Get value counts for the binary categorization
binary_value_counts = df_title['has_entities'].value_counts()

# Print both results
print("Entity Count Value Counts:")
print(entity_count_value_counts)

print("\nBinary Categorization (0 vs. More Than 0):")
print(binary_value_counts)

Entity Count Value Counts:
entity_count
1     489466
0     403970
2     135840
3      23953
4       3845
5        639
6        120
7         26
8          9
9          2
10         1
Name: count, dtype: int64

Binary Categorization (0 vs. More Than 0):
has_entities
1    653901
0    403970
Name: count, dtype: int64


In [48]:
# Filter the rows where the 'entity_count' is 10
rows_with_10_entities = df_title[df_title['entity_count'] == 10]

rows_with_10_entities

uid                                              title  \
42096  9021007  Brain anomalies, retardation of mentality and ...   

                                  disease_entities_spacy  entity_count  \
42096  [Brain anomalies, dysplasia, skeletal malforma...            10   

       has_entities  
42096             1

We can observe that model classify only around 65% of rows. We will first determine how many empty rows exist in the `abstract` variable. 
After assessing this, we will decide on the next steps based on the extent of overlap and the overall data quality.

### 4.3  SciSpacy Abstract

Processing `Abstract` with SciSpacy model

In [49]:
if __name__ == "__main__":
    file_path = "Data/2.Processed/ModellingData/P2_abstract.parquet"
    batch_size = 100_000  # Define your desired chunk size
    
    df_abstract = read_parquet_in_batches_with_progress(file_path, batch_size)
    
    print(f"\nFinal DataFrame with {len(df_abstract)} rows:")

Processing Batches:   0%|          | 0/1057871 [00:00<?, ?rows/s]

Processed Chunk 1: 100000 rows
Processed Chunk 2: 100000 rows
Processed Chunk 3: 100000 rows
Processed Chunk 4: 100000 rows
Processed Chunk 5: 100000 rows
Processed Chunk 6: 100000 rows
Processed Chunk 7: 100000 rows
Processed Chunk 8: 100000 rows
Processed Chunk 9: 100000 rows
Processed Chunk 10: 100000 rows
Processed Chunk 11: 57871 rows

Final DataFrame with 1057871 rows:


In [50]:
df_abstract.head()

uid                                           abstract
0  10186596  General: This article observes that, despite t...
1  10186588  General: Health promotion is a major component...
2  10186587  General: Health care reform in the United Stat...
3  10163501  General: The Cavitron Ultrasonic Surgical Aspi...
4  10157383  General: Previous work has documented large di...

In [51]:
###############################################################################
# COMPLETE CODE: CHUNK-BASED DISEASE EXTRACTION (BC5CDR) + TIME LEFT ESTIMATE
###############################################################################

###############################################################################
# 1) LOAD BC5CDR MODEL, DISABLING COMPONENTS FOR SPEED
###############################################################################
try:
    nlp_bc5cdr = spacy.load(
        "en_ner_bc5cdr_md", 
        disable=["tagger", "parser", "attribute_ruler", "lemmatizer"]
    )
except Exception as e:
    print("Could not load 'en_ner_bc5cdr_md'. Make sure you installed:")
    print("  pip install scispacy")
    print("  pip install en_ner_bc5cdr_md-0.5.4.tar.gz (or your local path)")
    raise e

def extract_diseases_spacy(doc):
    """
    Extract disease mentions from BC5CDR model. (ent.label_ in {CHEMICAL, DISEASE})
    We only keep label == 'DISEASE'.
    """
    diseases = []
    for ent in doc.ents:
        if ent.label_ == "DISEASE":
            diseases.append(ent.text)
    return diseases

###############################################################################
# 2) CHUNK PROCESSING WITH RESUME & TIME REMAIN ESTIMATE
###############################################################################
def process_diseases_in_chunks_with_resume(
    df,
    text_col="title",
    chunk_size=10_000,
    batch_size=32,
    save_path="partial_bc5cdr.parquet"
):
    """
    - df: main DataFrame
    - text_col: column with text to process
    - chunk_size: # of rows per chunk
    - batch_size: # docs per nlp.pipe() batch
    - save_path: Parquet file to store partial/final results

    1) Resumes from an existing partial file if it exists.
    2) Processes row by row in chunks, each chunk using spaCy's pipe for faster NER.
    3) Shows a progress bar + estimates time left based on chunk durations.
    4) Saves partial results after each chunk, then a final full save.
    5) The disease mentions get stored in df["disease_entities_spacy"].
    """

    df = df.reset_index(drop=True)

    # Initialize the column if absent
    if "disease_entities_spacy" not in df.columns:
        df["disease_entities_spacy"] = None

    # Figure out how many rows are already done if partial file is found
    start_idx = 0
    if os.path.exists(save_path):
        try:
            partial_df = pd.read_parquet(save_path)
            if "disease_entities_spacy" in partial_df.columns:
                df["disease_entities_spacy"] = partial_df["disease_entities_spacy"]
                done_mask = df["disease_entities_spacy"].notna()
                done_rows = done_mask.sum()
                start_idx = done_rows
                print(f"Resuming from row {start_idx} based on partial file {save_path}.")
            else:
                print(f"WARNING: {save_path} lacks 'disease_entities_spacy'. Starting fresh.")
        except Exception as e:
            print(f"Error reading partial file {save_path}: {e}")
            print("Starting from scratch.")
    else:
        print("No partial file found. Starting from scratch.")

    total_rows = len(df)
    if start_idx >= total_rows:
        print(f"All {total_rows} rows processed. Nothing to do.")
        return df

    # Calculate how many chunks remain
    remaining = total_rows - start_idx
    num_chunks = (remaining + chunk_size - 1) // chunk_size
    print(f"Starting chunked processing from row {start_idx}/{total_rows}, "
          f"{remaining} rows left, {num_chunks} chunks.\n")

    cur_row = start_idx
    chunk_times = []  # keep track of each chunk's duration to estimate time left

    with tqdm(total=num_chunks, desc="Processing Chunks", unit="chunk") as pbar:
        for i in range(num_chunks):
            chunk_start_time = time.time()

            end_idx = min(cur_row + chunk_size, total_rows)
            chunk = df.iloc[cur_row:end_idx].copy()
            texts = chunk[text_col].fillna("").tolist()

            # We'll store the results
            results = []

            # Use spaCy pipe in batch
            for doc in nlp_bc5cdr.pipe(texts, batch_size=batch_size):
                diseases = extract_diseases_spacy(doc)
                results.append(diseases)

            # Store in chunk and main df
            chunk["disease_entities_spacy"] = results
            df.iloc[cur_row:end_idx, df.columns.get_loc("disease_entities_spacy")] = chunk["disease_entities_spacy"]

            # Partial save
            df.iloc[:end_idx].to_parquet(save_path, index=False)

            # Chunk timing
            chunk_duration = time.time() - chunk_start_time
            chunk_times.append(chunk_duration)
            chunks_done = i + 1
            chunks_left = num_chunks - chunks_done
            # average chunk time so far
            avg_chunk_time = sum(chunk_times) / chunks_done
            est_time_left = avg_chunk_time * chunks_left

            # Update progress bar description with estimated time left
            pbar.set_postfix({
                "Last Chunk Time": f"{chunk_duration:.1f}s",
                "Est. Time Left": f"{est_time_left/60:.1f} min"
            })
            pbar.update(1)

            cur_row = end_idx

    # Final full save
    df.to_parquet(save_path, index=False)
    print(f"All done! Full results saved to {save_path}.\n")
    return df

###############################################################################
# USAGE
###############################################################################
if __name__ == "__main__":

    # Adjust chunk_size, batch_size to fit your environment
    df_abstract = process_diseases_in_chunks_with_resume(
        df_abstract,
        text_col="abstract",
        chunk_size=10_000,       # small chunk for demo
        batch_size=64,       # small batch for demo
        save_path="Data/2.Processed/ModellingData/P3_bc5cdr_results_abstract.parquet"
    )

    # Inspect final results
    df_abstract[["abstract", "disease_entities_spacy"]]

Resuming from row 1057871 based on partial file Data/2.Processed/ModellingData/P3_bc5cdr_results_abstract.parquet.
All 1057871 rows processed. Nothing to do.


In [52]:
df_abstract.head()

uid                                           abstract  \
0  10186596  General: This article observes that, despite t...   
1  10186588  General: Health promotion is a major component...   
2  10186587  General: Health care reform in the United Stat...   
3  10163501  General: The Cavitron Ultrasonic Surgical Aspi...   
4  10157383  General: Previous work has documented large di...   

                              disease_entities_spacy  
0  [human immunodeficiency virus (HIV) disease, a...  
1                                                 []  
2                                                 []  
3  [carcinoma of the ovary, and one each had, tub...  
4  [renal failure, renal failure, end stage renal...

In [54]:
# Count the number of elements in each list inside 'disease_entities_spacy'
df_abstract['entity_count'] = df_abstract['disease_entities_spacy'].apply(len)

# 1. Value counts of the number of entities in lists
entity_count_value_counts = df_abstract['entity_count'].value_counts()

# 2. Binary categorization: 0 count or more than 0
df_abstract['has_entities'] = df_abstract['entity_count'].apply(lambda x: 1 if x > 0 else 0)

# Get value counts for the binary categorization
binary_value_counts = df_abstract['has_entities'].value_counts()

# Print both results
print("Entity Count Value Counts:")
print(entity_count_value_counts)

print("\nBinary Categorization (0 vs. More Than 0):")
print(binary_value_counts)

Entity Count Value Counts:
entity_count
2      93178
3      92200
1      91642
4      89276
0      87103
       ...  
63         1
85         1
75         1
154        1
81         1
Name: count, Length: 73, dtype: int64

Binary Categorization (0 vs. More Than 0):
has_entities
1    970768
0     87103
Name: count, dtype: int64


 As part of the analysis, we also compared rows with empty entities in titles and abstracts to check how they intersect.

In [56]:
# Merge DataFrames on the 'id' column
merged_df = pd.merge(
    df_abstract[['uid', 'has_entities']], 
    df_title[['uid', 'has_entities']], 
    on='uid', 
    suffixes=('_abstract', '_title')
)

# Analyze rows based on their entity presence
no_entities_abstract = merged_df['has_entities_abstract'] == 0
no_entities_title = merged_df['has_entities_title'] == 0

# Count rows with:
# 1. No entities in both abstract and title
no_entities_both = merged_df[no_entities_abstract & no_entities_title].shape[0]

# 2. No entities in the abstract but entities in the title
no_entities_abstract_only = merged_df[no_entities_abstract & ~no_entities_title].shape[0]

# 3. No entities in the title but entities in the abstract
no_entities_title_only = merged_df[~no_entities_abstract & no_entities_title].shape[0]

# 4. Entities in both
entities_in_both = merged_df[~no_entities_abstract & ~no_entities_title].shape[0]

# Print the results
print("Summary of Rows with Entities:")
print(f"Rows with no entities in both abstract and title: {no_entities_both}")
print(f"Rows with no entities in abstract but entities in title: {no_entities_abstract_only}")
print(f"Rows with no entities in title but entities in abstract: {no_entities_title_only}")
print(f"Rows with entities in both abstract and title: {entities_in_both}")


Summary of Rows with Entities:
Rows with no entities in both abstract and title: 80868
Rows with no entities in abstract but entities in title: 6235
Rows with no entities in title but entities in abstract: 323102
Rows with entities in both abstract and title: 647666


### 4.4 Conclusions from SciSpacy Title and Abstracts

**Pros**:

Captures multi-word diseases, synonyms.
Doesn’t require you to maintain a dictionary.
The model can label “Parkinson’s disease,” “type 2 diabetes,” etc.

**Cons**:

Dependent on the model’s coverage and accuracy.
Takes more time than a simple dictionary approach.


Based on this, we now focus on the **80,868** rows that lack entities in both abstract and title. For these rows, we will perform a search through key *MeSH keywords terms* to check if any tokens are present.

**If no matching tokens are found:**

*These rows may need to be removed entirely.*

*Alternatively, we can explore inputting values from where we have done simple tokenization on another column.

## 5. Mesh_terms

Continuation of exploring lack of tokens related to diseases for ~ 80k records

In [77]:
df["mesh_list"] = (
    df["mesh_terms"]
    .fillna("")  #
    .str.split(";")
    .apply(lambda x: [m.strip() for m in x if m.strip()])  
)

In [78]:
mesh_counter = Counter()
for mesh_terms in df["mesh_list"]:
    mesh_counter.update(mesh_terms)

mesh_freq_df = pd.DataFrame(mesh_counter.most_common(), columns=["mesh_term", "count"])
mesh_freq_df.head(20)


mesh_term    count
0                      Humans  1057871
1                      Female   472540
2                        Male   432617
3                 Middle Aged   289180
4                       Adult   283915
5                        Aged   227184
6                     Animals   181045
7                  Adolescent   114072
8                Risk Factors   102561
9                       Child    96124
10          Treatment Outcome    95126
11      Retrospective Studies    93845
12          Aged, 80 and over    84418
13              United States    83743
14                       Mice    67297
15                Young Adult    64885
16  Severity of Illness Index    53709
17           Child, Preschool    52504
18        Prospective Studies    46072
19          Follow-Up Studies    45577

In [79]:
# Explode the list so each row in df_exploded is one MeSH term
df_exploded = df.explode("mesh_list")
# Then we can do a value_counts on the single item
mesh_freq = df_exploded["mesh_list"].value_counts(dropna=False)
print("Number of unique MeSH terms:", len(mesh_freq))
print("Top 20 MeSH terms:")
print(mesh_freq.head(20))

Number of unique MeSH terms: 27087
Top 20 MeSH terms:
mesh_list
Humans                       1057871
Female                        472540
Male                          432617
Middle Aged                   289180
Adult                         283915
Aged                          227184
Animals                       181045
Adolescent                    114072
Risk Factors                  102561
Child                          96124
Treatment Outcome              95126
Retrospective Studies          93845
Aged, 80 and over              84418
United States                  83743
Mice                           67297
Young Adult                    64885
Severity of Illness Index      53709
Child, Preschool               52504
Prospective Studies            46072
Follow-Up Studies              45577
Name: count, dtype: int64


In [80]:
df_mesh_list = df[['uid', 'mesh_list']].copy()

In [81]:
folder_path = "Data/2.Processed/ModellingData"

file_name_mesh_list = "P2_mesh_list.parquet"

file_path_mesh_list = os.path.join(folder_path, file_name_mesh_list)

# 1. Save the DataFrame as a single Parquet file
df_mesh_list.to_parquet(file_path_mesh_list, index=False, compression="snappy")
print(f"DataFrame saved as a single Parquet file: {file_path_mesh_list}")

DataFrame saved as a single Parquet file: Data/2.Processed/ModellingData\P2_mesh_list.parquet


In [82]:
###############################################################################
# 1) LOAD BC5CDR MODEL, DISABLING COMPONENTS FOR SPEED
###############################################################################
try:
    nlp_bc5cdr = spacy.load(
        "en_ner_bc5cdr_md", 
        disable=["tagger", "parser", "attribute_ruler", "lemmatizer"]
    )
except Exception as e:
    print("Could not load 'en_ner_bc5cdr_md'. Make sure you installed:")
    print("  pip install scispacy")
    print("  pip install en_ner_bc5cdr_md-0.5.4.tar.gz (or your local path)")
    raise e

def extract_diseases_spacy(doc):
    """
    Extract disease mentions from BC5CDR model. (ent.label_ in {CHEMICAL, DISEASE})
    We only keep label == 'DISEASE'.
    """
    diseases = []
    for ent in doc.ents:
        if ent.label_ == "DISEASE":
            diseases.append(ent.text)
    return diseases

###############################################################################
# 2) CHUNK PROCESSING WITH RESUME & TIME REMAIN ESTIMATE
###############################################################################
def process_diseases_in_chunks_with_resume(
    df,
    text_col="title",
    chunk_size=10_000,
    batch_size=32,
    save_path="partial_bc5cdr.parquet"
):
    """
    - df: main DataFrame
    - text_col: column with text to process
    - chunk_size: # of rows per chunk
    - batch_size: # docs per nlp.pipe() batch
    - save_path: Parquet file to store partial/final results

    1) Resumes from an existing partial file if it exists.
    2) Processes row by row in chunks, each chunk using spaCy's pipe for faster NER.
    3) Shows a progress bar + estimates time left based on chunk durations.
    4) Saves partial results after each chunk, then a final full save.
    5) The disease mentions get stored in df["disease_entities_spacy"].
    """
    # Reset index so row order is stable
    df = df.reset_index(drop=True)

    # Initialize the column if absent
    if "disease_entities_spacy" not in df.columns:
        df["disease_entities_spacy"] = None

    # Figure out how many rows are already done if partial file is found
    start_idx = 0
    if os.path.exists(save_path):
        try:
            partial_df = pd.read_parquet(save_path)
            if "disease_entities_spacy" in partial_df.columns:
                df["disease_entities_spacy"] = partial_df["disease_entities_spacy"]
                done_mask = df["disease_entities_spacy"].notna()
                done_rows = done_mask.sum()
                start_idx = done_rows
                print(f"Resuming from row {start_idx} based on partial file {save_path}.")
            else:
                print(f"WARNING: {save_path} lacks 'disease_entities_spacy'. Starting fresh.")
        except Exception as e:
            print(f"Error reading partial file {save_path}: {e}")
            print("Starting from scratch.")
    else:
        print("No partial file found. Starting from scratch.")

    total_rows = len(df)
    if start_idx >= total_rows:
        print(f"All {total_rows} rows processed. Nothing to do.")
        return df

    # Calculate how many chunks remain
    remaining = total_rows - start_idx
    num_chunks = (remaining + chunk_size - 1) // chunk_size
    print(f"Starting chunked processing from row {start_idx}/{total_rows}, "
          f"{remaining} rows left, {num_chunks} chunks.\n")

    cur_row = start_idx
    chunk_times = []  # keep track of each chunk's duration to estimate time left

    # Initialize the progress bar
    with tqdm(total=num_chunks, desc="Processing Chunks", unit="chunk") as pbar:
        for i in range(num_chunks):
            chunk_start_time = time.time()

            end_idx = min(cur_row + chunk_size, total_rows)
            chunk = df.iloc[cur_row:end_idx].copy()
            texts = chunk[text_col].fillna("").tolist()

            # We'll store the results
            results = []

            # Use spaCy pipe in batch
            for doc in nlp_bc5cdr.pipe(texts, batch_size=batch_size):
                diseases = extract_diseases_spacy(doc)
                results.append(diseases)

            # Store in chunk and main df
            chunk["disease_entities_spacy"] = results
            df.iloc[cur_row:end_idx, df.columns.get_loc("disease_entities_spacy")] = chunk["disease_entities_spacy"]

            # Partial save
            df.iloc[:end_idx].to_parquet(save_path, index=False)

            # Chunk timing
            chunk_duration = time.time() - chunk_start_time
            chunk_times.append(chunk_duration)
            chunks_done = i + 1
            chunks_left = num_chunks - chunks_done
            # average chunk time so far
            avg_chunk_time = sum(chunk_times) / chunks_done
            est_time_left = avg_chunk_time * chunks_left

            # Update progress bar description with estimated time left
            pbar.set_postfix({
                "Last Chunk Time": f"{chunk_duration:.1f}s",
                "Est. Time Left": f"{est_time_left/60:.1f} min"
            })
            pbar.update(1)

            cur_row = end_idx

    # Final full save
    df.to_parquet(save_path, index=False)
    print(f"All done! Full results saved to {save_path}.\n")
    return df

###############################################################################
# EXAMPLE USAGE
###############################################################################
if __name__ == "__main__":

    # Convert list of MeSH terms to a single string per row
    df_mesh_list["mesh_list_text"] = df_mesh_list["mesh_list"].apply(lambda x: " ".join(x) if isinstance(x, list) else str(x))

    # Adjust chunk_size, batch_size to fit your environment
    df_mesh_list = process_diseases_in_chunks_with_resume(
        df_mesh_list,
        text_col="mesh_list_text",
        chunk_size=10_000,       # small chunk for demo
        batch_size=64,       # small batch for demo
        save_path="Data/2.Processed/ModellingData/P3_bc5cdr_results_mesh_keywords.parquet"
    )

    # Inspect final results
    df_mesh_list[["mesh_list_text", "disease_entities_spacy"]]

No partial file found. Starting from scratch.
Starting chunked processing from row 0/1057871, 1057871 rows left, 106 chunks.



Processing Chunks:   0%|          | 0/106 [00:00<?, ?chunk/s]

All done! Full results saved to Data/2.Processed/ModellingData/P3.2_bc5cdr_results_mesh_keywords.parquet.



In [83]:
df_mesh_list.head()

uid                                          mesh_list  \
0  10186596  [Financing, Government, HIV Infections, Health...   
1  10186588  [Female, Health Education, Health Promotion, H...   
2  10186587  [Delivery of Health Care, Female, Health Care ...   
3  10163501  [Adenocarcinoma, Fallopian Tube Neoplasms, Fem...   
4  10157383  [Adolescent, Adult, Black or African American,...   

                                      mesh_list_text  \
0  Financing, Government HIV Infections Health Ca...   
1  Female Health Education Health Promotion Human...   
2  Delivery of Health Care Female Health Care Ref...   
3  Adenocarcinoma Fallopian Tube Neoplasms Female...   
4  Adolescent Adult Black or African American Asi...   

                           disease_entities_spacy  
0                                [HIV Infections]  
1                                              []  
2                                              []  
3  [Adenocarcinoma, Neoplasms, Ovarian Neoplasms]  
4                       [American Kidney Failure]

In [84]:
if __name__ == "__main__":
    batch_size = 100_000  # Define your desired chunk size

    # File paths
    file_mesh = "Data/2.Processed/ModellingData/P3_bc5cdr_results_mesh_keywords.parquet"
    file_all = "Data/2.Processed/ModellingData/P4_final_merged.parquet"

    # Read the abstract and title datasets
    df_mesh_list = read_parquet_in_batches_with_progress(file_mesh, batch_size)
    df = read_parquet_in_batches_with_progress(file_all, batch_size)

    # Rename columns
    df_mesh_list.rename(columns={"disease_entities_spacy": "disease_mesh_terms_spacy"}, inplace=True)

    # Select only the necessary columns for merging
    df_mesh_list = df_mesh_list[["uid", "disease_mesh_terms_spacy"]]

    # Read the main dataset
    df_all = read_parquet_in_batches_with_progress(file_all, batch_size)

    # Merge with the main dataset
    df_final = pd.merge(df_all, df_mesh_list, on="uid", how="inner")

    print(f"\nFinal DataFrame with {len(df_final)} rows:")

Processing Batches:   0%|          | 0/1057871 [00:00<?, ?rows/s]

Processed Chunk 1: 100000 rows
Processed Chunk 2: 100000 rows
Processed Chunk 3: 100000 rows
Processed Chunk 4: 100000 rows
Processed Chunk 5: 100000 rows
Processed Chunk 6: 100000 rows
Processed Chunk 7: 100000 rows
Processed Chunk 8: 100000 rows
Processed Chunk 9: 100000 rows
Processed Chunk 10: 100000 rows
Processed Chunk 11: 57871 rows


Processing Batches:   0%|          | 0/1057871 [00:00<?, ?rows/s]

Processed Chunk 1: 100000 rows
Processed Chunk 2: 100000 rows
Processed Chunk 3: 100000 rows
Processed Chunk 4: 100000 rows
Processed Chunk 5: 100000 rows
Processed Chunk 6: 100000 rows
Processed Chunk 7: 100000 rows
Processed Chunk 8: 100000 rows
Processed Chunk 9: 100000 rows
Processed Chunk 10: 100000 rows
Processed Chunk 11: 57871 rows


Processing Batches:   0%|          | 0/1057871 [00:00<?, ?rows/s]

Processed Chunk 1: 100000 rows
Processed Chunk 2: 100000 rows
Processed Chunk 3: 100000 rows
Processed Chunk 4: 100000 rows
Processed Chunk 5: 100000 rows
Processed Chunk 6: 100000 rows
Processed Chunk 7: 100000 rows
Processed Chunk 8: 100000 rows
Processed Chunk 9: 100000 rows
Processed Chunk 10: 100000 rows
Processed Chunk 11: 57871 rows

Final DataFrame with 1057871 rows:


In [85]:
df_final.copy()

uid                                              title  \
0        10186596  The potential impact of health care reform on ...   
1        10186588  New Jersey health promotion and disease preven...   
2        10186587  Who will provide preventive services? The chan...   
3        10163501  Cytoreduction of small intestine metastases us...   
4        10157383  Racial differences in access to kidney transpl...   
...           ...                                                ...   
1057866  35532046               Mental health help-seeking in China.   
1057867  35324349  Outcomes of Adenotonsillectomy for Obstructive...   
1057868  35274996  The Role of Puerarin in Chronic Wounds: A Revi...   
1057869  35243895  The Role of AMP-activated Protein Kinase in Ox...   
1057870  34933609  Spontaneous resolution of cerebral arterioveno...   

                                                   journal  \
0        Journal of public health management and practi...   
1        Journal of public health management and practi...   
2        Journal of public health management and practi...   
3                           Journal of gynecologic surgery   
4                             Health care financing review   
...                                                    ...   
1057866       Journal of mental health (Abingdon, England)   
1057867                        Ear, nose, & throat journal   
1057868  The international journal of lower extremity w...   
1057869                     Antioxidants & redox signaling   
1057870                    British journal of neurosurgery   

                                                  abstract  \
0        General: This article observes that, despite t...   
1        General: Health promotion is a major component...   
2        General: Health care reform in the United Stat...   
3        General: The Cavitron Ultrasonic Surgical Aspi...   
4        General: Previous work has documented large di...   
...                                                    ...   
1057866  BACKGROUND: In China, mental health disorders ...   
1057867  General: Objectives: To identify predictors of...   
1057868  General: Chronic wounds have a high disease bu...   
1057869  General: Significance: Evidence for a role for...   
1057870  BACKGROUND: Cerebral arteriovenous malformatio...   

                                                   authors  \
0                                    Auerbach J; McGuire J   
1                                               Louria D B   
2                        Pearson T A; Spencer M; Jenkins P   
3                                              Adelson M D   
4                                               Eggers P W   
...                                                    ...   
1057866  Gearing Robin Edward; Brewer Kathryne B; Leung...   
1057867  Rayasam Swathi S; Abijay Claire; Johnson Romai...   
1057868    Anvery Noor; Selim Abdulhafez; Khachemoune Amor   
1057869  Currais Antonio; Kepchia Devin; Liang Zhibin; ...   
1057870  Kumar Jay I; Wasserman Jacob; Heller Robert S;...   

                                              affiliations  \
0        HIV/AIDS Bureau, Massachusetts Department of P...   
1        Department of Preventive Medicine and Communit...   
2        Mary Imogene Bassett Research Institute, Coope...   
3        Department of Obstetrics and Gynecology, Crous...   
4        Office of Research and Demonstrations, Health ...   
...                                                    ...   
1057866  Center for Mental Health Research and Innovati...   
1057867  UT Southwestern Medical School, Dallas, TX, US...   
1057868  SUNY Downstate Medical Center, Brooklyn, NY, U...   
1057869  Cellular Neurobiology Laboratory, Salk Institu...   
1057870  Department of Neurosurgery and Brain Repair, U...   

                                                mesh_terms  \
0        Financing, Government; HIV Infections; Health ...   
1        Female; Health Education; Health Pro

In [86]:
if __name__ == "__main__":

    folder_path = "Data/2.Processed/ModellingData"
    final_file = "P5_final_new.parquet"
    batch_size = 100_000  # e.g. if you want ~10 batches

    result_path = save_and_merge_in_batches(
        df=df_final,
        batch_size=batch_size,
        output_folder=folder_path,
        final_filename=final_file,
        temp_batch_prefix="temp_batch_"
    )

    print(f"All done. Merged file at: {result_path}")

Splitting DataFrame of 1057871 rows into 11 batches (size=100000).


Saving Batches:   0%|          | 0/11 [00:00<?, ?batch/s]

  -> Batch 1 rows [0:100000] saved to Data/2.Processed/ModellingData\temp_batches\temp_batch_1.parquet
  -> Batch 2 rows [100000:200000] saved to Data/2.Processed/ModellingData\temp_batches\temp_batch_2.parquet
  -> Batch 3 rows [200000:300000] saved to Data/2.Processed/ModellingData\temp_batches\temp_batch_3.parquet
  -> Batch 4 rows [300000:400000] saved to Data/2.Processed/ModellingData\temp_batches\temp_batch_4.parquet
  -> Batch 5 rows [400000:500000] saved to Data/2.Processed/ModellingData\temp_batches\temp_batch_5.parquet
  -> Batch 6 rows [500000:600000] saved to Data/2.Processed/ModellingData\temp_batches\temp_batch_6.parquet
  -> Batch 7 rows [600000:700000] saved to Data/2.Processed/ModellingData\temp_batches\temp_batch_7.parquet
  -> Batch 8 rows [700000:800000] saved to Data/2.Processed/ModellingData\temp_batches\temp_batch_8.parquet
  -> Batch 9 rows [800000:900000] saved to Data/2.Processed/ModellingData\temp_batches\temp_batch_9.parquet
  -> Batch 10 rows [900000:100000

Merging Batches:   0%|          | 0/11 [00:00<?, ?file/s]

Final merged DataFrame saved as: Data/2.Processed/ModellingData\P5_final_new.parquet

Temporary batch files removed. All done!
All done. Merged file at: Data/2.Processed/ModellingData\P5_final_new.parquet


In [90]:
#%reset

In [104]:
# Check for the absence of tokens in each variable
no_tokens_abstract = df['disease_abstract_spacy'].apply(len) == 0
no_tokens_title = df['disease_title_spacy'].apply(len) == 0
no_tokens_mesh_terms = df['disease_mesh_terms_spacy'].apply(len) == 0

# Calculate insights
# 1. No tokens in all three variables
no_tokens_in_all = (no_tokens_abstract & no_tokens_title & no_tokens_mesh_terms).sum()

# 2. No tokens in abstract only
no_tokens_in_abstract_only = (no_tokens_abstract & ~no_tokens_title & ~no_tokens_mesh_terms).sum()

# 3. No tokens in title only
no_tokens_in_title_only = (~no_tokens_abstract & no_tokens_title & ~no_tokens_mesh_terms).sum()

# 4. No tokens in mesh terms only
no_tokens_in_mesh_terms_only = (~no_tokens_abstract & ~no_tokens_title & no_tokens_mesh_terms).sum()

# 5. Tokens missing in at least one variable
no_tokens_in_at_least_one = (no_tokens_abstract | no_tokens_title | no_tokens_mesh_terms).sum()

# 6. Tokens missing in all variables
no_tokens_in_all = (no_tokens_abstract & no_tokens_title & no_tokens_mesh_terms).sum()

# Print insights
print("Summary of Insights:")
print(f"Rows with no tokens in all three variables: {no_tokens_in_all}")
print(f"Rows with no tokens in abstract only: {no_tokens_in_abstract_only}")
print(f"Rows with no tokens in title only: {no_tokens_in_title_only}")
print(f"Rows with no tokens in mesh terms only: {no_tokens_in_mesh_terms_only}")
print(f"Rows with no tokens in at least one variable: {no_tokens_in_at_least_one}")
print(f"Rows with no tokens in all variables: {no_tokens_in_all}")

Summary of Insights:
Rows with no tokens in all three variables: 60247
Rows with no tokens in abstract only: 3553
Rows with no tokens in title only: 179606
Rows with no tokens in mesh terms only: 92985
Rows with no tokens in at least one variable: 503190
Rows with no tokens in all variables: 60247


There are still over 60000 records without clasified medical tokens
Rows with no tokens in all variables: 60247

In [ ]:
# Check for the presence or absence of tokens in each variable
no_tokens_abstract = df['disease_abstract_spacy'].apply(len) == 0
no_tokens_title = df['disease_title_spacy'].apply(len) == 0
has_tokens_mesh_terms = df['disease_mesh_terms_spacy'].apply(len) > 0

# Filter rows: Tokens in mesh terms but no tokens in abstract and title
rows_with_tokens_in_mesh_only = df[no_tokens_abstract & no_tokens_title & has_tokens_mesh_terms]

# Display the filtered rows
print(f"Number of rows with tokens in mesh terms but no tokens in abstract and title: {len(rows_with_tokens_in_mesh_only)}")
rows_with_tokens_in_mesh_only


Number of rows with tokens in mesh terms but no tokens in abstract and title: 20621


uid                                              title  \
6        10142084  Impact of home-based respite care on families ...   
15        7792449  Multiple hypothesis tests in multiple investig...   
68       10101381  Voluntary newborn HIV-1 antibody testing: a su...   
78        9447030  Enhancing function in life transitions and ser...   
86        9385102  Assessing gamma frailty models for clustered f...   
...           ...                                                ...   
1057659  38436994  Ferumoxytol-Enhanced Cardiac Cine MRI Reconstr...   
1057756  38073067  Elucidating structural variability in p53 conf...   
1057765  38019373  Bon Sante (Good Health): Factors Influencing P...   
1057777  37941422  Does doffing the FEES Box generate a significa...   
1057841  37094286  Healthy Eating Index and Dietary Inflammatory ...   

                                                   journal  \
6        Children's health care : journal of the Associ...   
15                                  Statistics in medicine   
68            Bulletin of the New York Academy of Medicine   
78                     Advanced practice nursing quarterly   
86                                  Lifetime data analysis   
...                                                    ...   
1057659       Journal of magnetic resonance imaging : JMRI   
1057756                           Cancer biology & therapy   
1057765    Journal of racial and ethnic health disparities   
1057777  International journal of speech-language patho...   
1057841      Journal of American college health : J of ACH   

                                                  abstract  \
6        General: The recent dramatic medical and techn...   
15       General: Inferential statistical methods have ...   
68       General: Harlem Hospital in New York City has ...   
78       General: Function, which encompasses functiona...   
86       General: Proportional hazards frailty models u...   
...                                                    ...   
1057659  BACKGROUND: Balanced steady-state free precess...   
1057756  General: Low molecular weight proteins and pro...   
1057765  BACKGROUND: The HIV/AIDS epidemic has dispropo...   
1057777  PURPOSE: The spread of airborne diseases, incl...   
1057841  OBJECTIVE: This cross-sectional study investig...   

                                                   authors  \
6                                              Sherman B R   
15                                   Caudill S P; Hill R H   
68                                 Abrams E J; Bateman D A   
78                          Fawcett J; Tulman L; Samarel N   
86                                     Shih J H; Louis T A   
...                                                    ...   
1057659  Gao Chang; Ming Zhengyang; Nguyen Kim-Lien; Pa...   
1057756  Parves Md Rimon; Solares Maria J; Dearnaley Wi...   
1057765  Sternberg Candice A; Daniel E Valerie; Marceli...   
1057777      Li Anne; Ganann Michelle G; Pisegna Jessica M   
1057841    Gieng John; Field Kiley D; Pignotti Giselle A P   

                                              affiliations  \
6        School of Public Health, State University of N...   
15       Division of Environmental Health Laboratory Sc...   
68       Department of Pediatrics, Harlem Hospital Cent...   
78       University of Pennsylvania School of Nursing, ...   
86       Office of Biostatistics Research, National Hea...   
...                                                    ...   
1057659  Department of Physics and Biology in Medicine,...   
1057756  Department of Biomedical Engineering, Pennsylv...   
1057765  Department of Medicine, University of Miami Mi...   
1057777  Department of Otolaryngology - Head and Neck S...   
1057841  Department of Nutrition, Food Science, and Pac...   

                                                mesh_terms  \
6        Adolescent; Caregivers; Child; Child Health Se...   
15       Chromatography, High Pressure Liquid

In [108]:
# Check for the absence of tokens in each column
no_tokens_abstract = df['disease_abstract_spacy'].apply(len) == 0
no_tokens_title = df['disease_title_spacy'].apply(len) == 0
no_tokens_mesh_terms = df['disease_mesh_terms_spacy'].apply(len) == 0

# Filter rows: No tokens in all three columns
rows_with_no_tokens_in_all = df[no_tokens_abstract & no_tokens_title & no_tokens_mesh_terms]

# Display the filtered rows
print(f"Number of rows with no tokens in all three columns: {len(rows_with_no_tokens_in_all)}")
rows_with_no_tokens_in_all


Number of rows with no tokens in all three columns: 60247


uid                                              title  \
1        10186588  New Jersey health promotion and disease preven...   
2        10186587  Who will provide preventive services? The chan...   
11        7792456  Combining National Health Interview Survey Dat...   
23        7746852   Steps along the pathway of V (D)J recombination.   
34        7701158  Confidence intervals, hypothesis tests, and sa...   
...           ...                                                ...   
1057776  37950146         The Neuroimmune System and the Cerebellum.   
1057788  37864504  The Healthy Caregiver? A Positive Impact of In...   
1057793  37843779  Dignified Resources and Coping Strategies Duri...   
1057838  37140155  Activity-Dependent Synapse Refinement: From Me...   
1057842  37087733  Structure and function of the TPR-domain immun...   

                                                   journal  \
1        Journal of public health management and practi...   
2        Journal of public health management and practi...   
11                                  Statistics in medicine   
23       Philosophical transactions of the Royal Societ...   
34                                  Statistics in medicine   
...                                                    ...   
1057776                       Cerebellum (London, England)   
1057788                        Journal of aging and health   
1057793    Journal of racial and ethnic health disparities   
1057838  The Neuroscientist : a review journal bringing...   
1057842                   Journal of cellular biochemistry   

                                                  abstract  \
1        General: Health promotion is a major component...   
2        General: Health care reform in the United Stat...   
11       General: This paper identifies issues, special...   
23       General: The mechanism of lymphoid-specific ge...   
34       General: The prevented fraction (PF) is the pr...   
...                                                    ...   
1057776  General: The recognition that there is an inna...   
1057788  OBJECTIVES: The current study examined whether...   
1057793  INTRODUCTION: Amid the spread of the novel cor...   
1057838  General: The refinement of immature neuronal n...   
1057842  General: Coordinated cochaperone interactions ...   

                                                   authors  \
1                                               Louria D B   
2                        Pearson T A; Spencer M; Jenkins P   
11                                    Botman S L; Jack S S   
23                                  Gellert M; McBlane J F   
34               Gargiullo P M; Rothenberg R B; Wilson H G   
...                                                    ...   
1057776                                      Gruol Donna L   
1057788  Bhattacharyya Kallol Kumar; Liu Yin; Das Gupta...   
1057793  Guan Alice; Cruz Tessa; Sowell Jamaica; Mathia...   
1057838  Nagappan-Chettiar Sivapratha; Burbridge Timoth...   
1057842  Soto Olga B; Ramirez Christian S; Koyani Rina;...   

                                              affiliations  \
1        Department of Preventive Medicine and Communit...   
2        Mary Imogene Bassett Research Institute, Coope...   
11       National Center for Health Statistics, Centers...   
23       Laboratory of Molecular Biology, National Inst...   
34       National Center for Chronic Disease Prevention...   
...                                                    ...   
1057776  Neuroscience Department, The Scripps Research ...   
1057788  Alzheimer's Disease and Dementia Research Cent...   
1057793  Department of Epidemiology and Biostatistics |...   
1057838  Department of Neurology, F.M. Kirby Neurobiolo...   
1057842  Department of Biological Sciences, Border Biom...   

                                                mesh_terms  \
1        Female; Health Education; Health Promotion; Hu...   
2        Delivery of Health Care; Female; Hea

In [110]:
# Define all columns to check for emptiness
columns_to_check = [
    'disease_abstract_spacy', 
    'disease_title_spacy', 
    'disease_mesh_terms_spacy', 
    'disease_title_tokens_simple', 
    'disease_title_tokens_hf', 
    'disease_abstract_tokens_simple', 
    'disease_abstract_tokens_hf'
]

# Check for emptiness in each column
conditions = [df[col].apply(len) == 0 for col in columns_to_check]

# Combine conditions: Check if all specified columns are empty for each row
all_empty_condition = conditions[0]
for condition in conditions[1:]:
    all_empty_condition &= condition

# Filter rows where all columns are empty
rows_with_all_columns_empty = df[all_empty_condition]

# Display the filtered rows
print(f"Number of rows with all specified columns empty: {len(rows_with_all_columns_empty)}")
rows_with_all_columns_empty

Number of rows with all specified columns empty: 54819


uid                                              title  \
1        10186588  New Jersey health promotion and disease preven...   
2        10186587  Who will provide preventive services? The chan...   
11        7792456  Combining National Health Interview Survey Dat...   
23        7746852   Steps along the pathway of V (D)J recombination.   
34        7701158  Confidence intervals, hypothesis tests, and sa...   
...           ...                                                ...   
1057758  38057655  Community Engagement in Behavioral Medicine: A...   
1057776  37950146         The Neuroimmune System and the Cerebellum.   
1057788  37864504  The Healthy Caregiver? A Positive Impact of In...   
1057838  37140155  Activity-Dependent Synapse Refinement: From Me...   
1057842  37087733  Structure and function of the TPR-domain immun...   

                                                   journal  \
1        Journal of public health management and practi...   
2        Journal of public health management and practi...   
11                                  Statistics in medicine   
23       Philosophical transactions of the Royal Societ...   
34                                  Statistics in medicine   
...                                                    ...   
1057758       International journal of behavioral medicine   
1057776                       Cerebellum (London, England)   
1057788                        Journal of aging and health   
1057838  The Neuroscientist : a review journal bringing...   
1057842                   Journal of cellular biochemistry   

                                                  abstract  \
1        General: Health promotion is a major component...   
2        General: Health care reform in the United Stat...   
11       General: This paper identifies issues, special...   
23       General: The mechanism of lymphoid-specific ge...   
34       General: The prevented fraction (PF) is the pr...   
...                                                    ...   
1057758  BACKGROUND: Behavioral medicine has made key c...   
1057776  General: The recognition that there is an inna...   
1057788  OBJECTIVES: The current study examined whether...   
1057838  General: The refinement of immature neuronal n...   
1057842  General: Coordinated cochaperone interactions ...   

                                                   authors  \
1                                               Louria D B   
2                        Pearson T A; Spencer M; Jenkins P   
11                                    Botman S L; Jack S S   
23                                  Gellert M; McBlane J F   
34               Gargiullo P M; Rothenberg R B; Wilson H G   
...                                                    ...   
1057758  Persad-Clem Reema; Ventura Liane M; Lyons Tier...   
1057776                                      Gruol Donna L   
1057788  Bhattacharyya Kallol Kumar; Liu Yin; Das Gupta...   
1057838  Nagappan-Chettiar Sivapratha; Burbridge Timoth...   
1057842  Soto Olga B; Ramirez Christian S; Koyani Rina;...   

                                              affiliations  \
1        Department of Preventive Medicine and Communit...   
2        Mary Imogene Bassett Research Institute, Coope...   
11       National Center for Health Statistics, Centers...   
23       Laboratory of Molecular Biology, National Inst...   
34       National Center for Chronic Disease Prevention...   
...                                                    ...   
1057758  School of Graduate Education, Geisinger Colleg...   
1057776  Neuroscience Department, The Scripps Research ...   
1057788  Alzheimer's Disease and Dementia Research Cent...   
1057838  Department of Neurology, F.M. Kirby Neurobiolo...   
1057842  Department of Biological Sciences, Border Biom...   

                                                mesh_terms  \
1        Female; Health Education; Health Promotion; Hu...   
2        Delivery of Health Care; Female; Hea

In [112]:
# Define the original and new columns
original_columns = ['disease_abstract_spacy', 'disease_title_spacy', 'disease_mesh_terms_spacy']
new_columns = ['disease_title_tokens_simple', 'disease_title_tokens_hf', 'disease_abstract_tokens_simple', 'disease_abstract_tokens_hf']

# Check for emptiness in the original columns
original_columns_empty = [df[col].apply(len) == 0 for col in original_columns]

# Check for non-emptiness in the new columns
new_columns_not_empty = [df[col].apply(len) > 0 for col in new_columns]

# Combine conditions: Original columns are empty, and new columns are not empty
original_empty_condition = original_columns_empty[0]
for condition in original_columns_empty[1:]:
    original_empty_condition &= condition

new_not_empty_condition = new_columns_not_empty[0]
for condition in new_columns_not_empty[1:]:
    new_not_empty_condition |= condition  # At least one of the new columns must not be empty

# Filter rows where original columns are empty but new columns are not empty
rows_with_new_columns_not_empty = df[original_empty_condition & new_not_empty_condition]

# Display the filtered rows
print(f"Number of rows where original columns are empty but new columns are not: {len(rows_with_new_columns_not_empty)}")
rows_with_new_columns_not_empty

Number of rows where original columns are empty but new columns are not: 5428


uid                                              title  \
114       9144076  Expression of nitric oxide synthase in human p...   
608       8563403  Cat 6 mo increases symptoms: online physician ...   
1005      7748586  Participation in health promotion programs by ...   
1237      7715982  Safety and immunogenicity of a cold-adapted in...   
1958      7483295  Nucleotide sequences of the neuraminidase gene...   
...           ...                                                ...   
1057651  38445666  Factors influencing adverse events following C...   
1057652  38445561  Parental intention on getting children COVID-1...   
1057716  38251822  Heterogeneity of provider preferences for HIV ...   
1057760  38054302  Concomitant administration of seasonal influen...   
1057793  37843779  Dignified Resources and Coping Strategies Duri...   

                                                   journal  \
114                                Journal of inflammation   
608      Proceedings. Symposium on Computer Application...   
1005               American journal of preventive medicine   
1237              The Pediatric infectious disease journal   
1958                                           Virus genes   
...                                                    ...   
1057651                Human vaccines & immunotherapeutics   
1057652                Human vaccines & immunotherapeutics   
1057716                   HIV research & clinical practice   
1057760                     Emerging microbes & infections   
1057793    Journal of racial and ethnic health disparities   

                                                  abstract  \
114      General: It has been clearly demonstrated in r...   
608      General: The physicians of the Children's Asth...   
1005     General: The Health Care Financing Administrat...   
1237     General: A safe and effective influenza vaccin...   
1958     General: The nucleotide sequences of the neura...   
...                                                    ...   
1057651  General: Various novel platform technologies h...   
1057652  General: Countries worldwide are facing challe...   
1057716  General: The PROMISE study assessed revisions ...   
1057760  General: Current clinical guidelines support t...   
1057793  INTRODUCTION: Amid the spread of the novel cor...   

                                                   authors  \
114      Amin A R; Attur M; Vyas P; Leszczynska-Piziak ...   
608      Lee M; Niemeyer D; Seilheimer D; Abramson S; L...   
1005            Lave J R; Ives D G; Traven N D; Kuller L H   
1237     Karron R A; Steinhoff M C; Subbarao E K; Wilso...   
1958     Klimov A I; Romanova J R; Egorov A Y; Lukashok...   
...                                                    ...   
1057651  Villanueva Paola; McDonald Ellie; Croda Julio;...   
1057652  Ahorsu Daniel Kwasi; Potenza Marc N; Lin Chung...   
1057716  Fong Chunki; Conte Madellena; Zimba Rebecca; C...   
1057760  Aydillo Teresa; Balsera-Manzanero Maria; Rojo-...   
1057793  Guan Alice; Cruz Tessa; Sowell Jamaica; Mathia...   

                                              affiliations  \
114      Department of Rheumatology, Hospital for Joint...   
608      Information Services, Texas Children's Hospita...   
1005     Department of Health Services Administration, ...   
1237     Department of International Health, School of ...   
1958     Influenza Branch, Centers for Disease Control ...   
...                                                    ...   
1057651  Department of Paediatrics, The University of M...   
1057652  Department of Special Education and Counsellin...   
1057716  Institute for Implementation Science in Popula...   
1057760  Department of Microbiology, Icahn School of Me...   
1057793  Department of Epidemiology and Biostatistics |...   

                                                mesh_terms  \
114      Adenosine Diphosphate Ribose; Animals; Base Se...   
608      Asthma; Hospital Information Systems

In [120]:
target_uids = [37843779]

filtered_rows_by_uid = df[df['uid'] == "37843779"]

print(f"Rows with target UIDs {target_uids}:")
filtered_rows_by_uid

Rows with target UIDs [37843779]:


uid                                              title  \
1057793  37843779  Dignified Resources and Coping Strategies Duri...   

                                                 journal  \
1057793  Journal of racial and ethnic health disparities   

                                                  abstract  \
1057793  INTRODUCTION: Amid the spread of the novel cor...   

                                                   authors  \
1057793  Guan Alice; Cruz Tessa; Sowell Jamaica; Mathia...   

                                              affiliations  \
1057793  Department of Epidemiology and Biostatistics |...   

                                                mesh_terms  \
1057793  Humans; COVID-19; Qualitative Research; Adult;...   

                                                  keywords coi_statement  \
1057793  COVID-19; Community-based participatory resear...           N/A   

        parsed_date  ...                            cleaned_title_tokens_hf  \
1057793  2024-12-01  ...  [[CLS], dig, ##nified, resources, coping, stra...   

                            cleaned_abstract_tokens_simple  \
1057793  [introduction, amid, spread, novel, coronaviru...   

                                cleaned_abstract_tokens_hf  \
1057793  [[CLS], introduction, amid, spread, novel, cor...   

        disease_title_tokens_simple disease_title_tokens_hf  \
1057793                     [covid]                      []   

        disease_abstract_tokens_simple disease_abstract_tokens_hf  \
1057793                 [covid, covid]                         []   

        disease_abstract_spacy disease_title_spacy disease_mesh_terms_spacy  
1057793                     []                  []                       []  

[1 rows x 21 columns]

In [ ]:
# Define all columns to check for emptiness
columns_to_check = [
    'disease_abstract_spacy', 
    'disease_title_spacy', 
    'disease_mesh_terms_spacy', 
    'disease_title_tokens_simple', 
    'disease_title_tokens_hf', 
    'disease_abstract_tokens_simple', 
    'disease_abstract_tokens_hf'
]

conditions = [df[col].apply(len) == 0 for col in columns_to_check]

all_empty_condition = conditions[0]
for condition in conditions[1:]:
    all_empty_condition &= condition

df_cleaned = df[~all_empty_condition]

print(f"Number of rows after removing those with all specified columns empty: {len(df_cleaned)}")
output_file_path = "Data/2.Processed/ModellingData/P6_cleaned_data.parquet"
df_cleaned.to_parquet(output_file_path, index=False, compression="snappy")
print(f"Cleaned DataFrame saved to: {output_file_path}")

## 6. Conclusions/Final Decision

**Final Decision: Data Retention vs. Row Removal** `title` + `abstract` + `mesh terms`


During the data processing pipeline, we faced a choice regarding whether to remove rows that lacked tokens related to illnesses. (there is still possibility to try and check these articles for any possible tokens there)

The goal was to ensure high-quality data for further analysis and modelling while retaining as much relevant information as possible.

**Choices Considered**:

Title only: Retain rows with illness-related tokens in the title.
*Result*: ~1,000,000 → 480,000 rows removed (~520,000 retained).

- Abstract + Title: Retain rows with tokens in either title or abstract.
*Result*: ~1,000,000 → 84,000 rows removed (~916,000 retained).

- Abstract + Title + MeSH terms: Include tokens found in MeSH terms.
*Result*: ~1,000,000 → 60,000rows removed (~940,000 retained).

- Abstract + Title + MeSH + Hybrid Filtering: Use advanced filtering (e.g., hybrid matching and simpler keyword matching).
*Result*: ~1,000,000 → 54,000 rows removed (~946,000 retained).

- Retain All Rows: Do not remove rows based on token presence.

**Final Decision**:
We chose Option 5 to retain all rows. This decision was based on the reasoning that data lacking illness-related tokens is not inherently irrelevant and there may be possibility to check these inputs (articles) and see what's the problem with them. 

By keeping all rows we additionaly:

- We maintain the integrity and diversity of the dataset.

- Downstream analyses remain flexible, as token filtering can be performed at a later stage if necessary.

- It enables broader exploration and modeling possibilities without prematurely discarding data.

- By taking this approach, the dataset remains inclusive, ensuring no potential insights are lost. This aligns with our goal of providing a comprehensive resource for PubMed data analysis.